package com.wos.dao.mapper;

import com.wos.pojo.ChargeType;

public interface ChargeTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_ChargeType
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    int deleteByPrimaryKey(String cguid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_ChargeType
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    int insert(ChargeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_ChargeType
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    int insertSelective(ChargeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_ChargeType
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    ChargeType selectByPrimaryKey(String cguid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_ChargeType
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    int updateByPrimaryKeySelective(ChargeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_ChargeType
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    int updateByPrimaryKey(ChargeType record);
}