package com.wos.dao.mapper;

import com.wos.pojo.ConfigMgtInfo;

public interface ConfigMgtInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ITSM_SERVICE_CONFIGUREMANAGEME
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    int insert(ConfigMgtInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ITSM_SERVICE_CONFIGUREMANAGEME
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    int insertSelective(ConfigMgtInfo record);
}