package com.wos.dao.mapper;

import com.wos.pojo.ConfigExpandInfo;

public interface ConfigExpandInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_ConManagerExpand
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    int insert(ConfigExpandInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_ConManagerExpand
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    int insertSelective(ConfigExpandInfo record);
}