package com.wos.dao.mapper;

import com.wos.pojo.Employee;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.cm_employee
     *
     * @mbggenerated Sun Jan 04 16:50:19 CST 2015
     */
    int deleteByPrimaryKey(String cguid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.cm_employee
     *
     * @mbggenerated Sun Jan 04 16:50:19 CST 2015
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.cm_employee
     *
     * @mbggenerated Sun Jan 04 16:50:19 CST 2015
     */
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.cm_employee
     *
     * @mbggenerated Sun Jan 04 16:50:19 CST 2015
     */
    Employee selectByPrimaryKey(String cguid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.cm_employee
     *
     * @mbggenerated Sun Jan 04 16:50:19 CST 2015
     */
    int updateByPrimaryKeySelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.cm_employee
     *
     * @mbggenerated Sun Jan 04 16:50:19 CST 2015
     */
    int updateByPrimaryKey(Employee record);
}