package com.wos.dao.mapper;

import java.util.List;

import com.wos.pojo.EnterpriseContacts;

public interface EnterpriseContactsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_base_EnterpriseContacts
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    int insert(EnterpriseContacts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_base_EnterpriseContacts
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    int insertSelective(EnterpriseContacts record);
    
    int updateAsCurrentContact(String cguid);
    
    List<EnterpriseContacts> findContactInfoByEnterpriseId(String enterpriseId);
}