package com.wos.dao.mapper;

import java.util.List;

import com.wos.pojo.EnterpriseAddress;

public interface EnterpriseAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_base_EnterpriseAddress
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    int insert(EnterpriseAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_base_EnterpriseAddress
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    int insertSelective(EnterpriseAddress record);
    List<EnterpriseAddress> getEnterpriseAddresses(String enterpriseId);
    
    int deleteByPrimaryKey(String cguid);
    
    int updateEnterpriseAddress(EnterpriseAddress record);
    
    int updateAsCurrentAddress(String cguid);
}