package com.wos.dao.mapper;

import com.wos.pojo.EnumerateInfo;

public interface EnumerateInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.AOS_BD_ENUMERATE
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    int insert(EnumerateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.AOS_BD_ENUMERATE
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    int insertSelective(EnumerateInfo record);
}