package com.wos.dao.mapper;

import com.wos.pojo.ExtendedAttribute;

public interface ExtendedAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_base_ExtendedAttribute
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    int insert(ExtendedAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_base_ExtendedAttribute
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    int insertSelective(ExtendedAttribute record);
}