package com.wos.dao.mapper;

import com.wos.pojo.InstallDocuDetail;

public interface InstallDocuDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_InstallDocuDetail
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    int insert(InstallDocuDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_InstallDocuDetail
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    int insertSelective(InstallDocuDetail record);
}