package com.wos.dao.mapper;

import com.wos.pojo.InstallDocuCofig;

public interface InstallDocuCofigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_InstallDocuCofing
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    int insert(InstallDocuCofig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_InstallDocuCofing
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    int insertSelective(InstallDocuCofig record);
}