package com.wos.dao.mapper;

import com.wos.pojo.InstallTemplate;
import com.wos.pojo.InstallTemplateExample;
import java.util.List;

public interface InstallTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_InstallTemplate
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    int deleteByPrimaryKey(String cguid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_InstallTemplate
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    int insert(InstallTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_InstallTemplate
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    int insertSelective(InstallTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_InstallTemplate
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    List<InstallTemplate> selectByExample(InstallTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_InstallTemplate
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    InstallTemplate selectByPrimaryKey(String cguid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_InstallTemplate
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    int updateByPrimaryKeySelective(InstallTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_InstallTemplate
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    int updateByPrimaryKey(InstallTemplate record);
    
    List<InstallTemplate> loadAllInstallTemplates();
}