package com.wos.dao.mapper;

import com.wos.pojo.MaintainDocument;

public interface MaintainDocumentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_MaintainDocument
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    int insert(MaintainDocument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_MaintainDocument
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    int insertSelective(MaintainDocument record);
}