package com.wos.dao.mapper;

import com.wos.pojo.Material;

public interface MaterialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.CM_Material
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    int insert(Material record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.CM_Material
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    int insertSelective(Material record);
}