package com.wos.dao.mapper;

import com.wos.pojo.MetaEntity;

public interface MetaEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.META_ENTITY
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    int insert(MetaEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.META_ENTITY
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    int insertSelective(MetaEntity record);
}