package com.wos.dao.mapper;

import com.wos.pojo.ServiceResponse;

public interface ServiceResponseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_ServiceResponse
     *
     * @mbggenerated Fri Dec 05 17:20:59 CST 2014
     */
    int insert(ServiceResponse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_ServiceResponse
     *
     * @mbggenerated Fri Dec 05 17:20:59 CST 2014
     */
    int insertSelective(ServiceResponse record);
}