package com.wos.dao.mapper;

import com.wos.pojo.Survey;

public interface SurveyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ITSM_BASE_SURVEY
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    int insert(Survey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.ITSM_BASE_SURVEY
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    int insertSelective(Survey record);
}