package com.wos.pojo;

public class AreaClass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.CM_AreaClass.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.CM_AreaClass.cCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ccode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.CM_AreaClass.cName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.CM_AreaClass.cRemark
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.CM_AreaClass.iStatus
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Short istatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.CM_AreaClass.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ctimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.CM_AreaClass.iLeaf
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Short ileaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.CM_AreaClass.cParentID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cparentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.CM_AreaClass.iLevel
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Short ilevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.CM_AreaClass.cHotCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String chotcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.CM_AreaClass.cFullCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cfullcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.CM_AreaClass.cInnerCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cinnercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.CM_AreaClass.CrmID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String crmid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.CM_AreaClass.cGUID
     *
     * @return the value of dbo.CM_AreaClass.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCguid() {
        return cguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.CM_AreaClass.cGUID
     *
     * @param cguid the value for dbo.CM_AreaClass.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCguid(String cguid) {
        this.cguid = cguid == null ? null : cguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.CM_AreaClass.cCode
     *
     * @return the value of dbo.CM_AreaClass.cCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCcode() {
        return ccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.CM_AreaClass.cCode
     *
     * @param ccode the value for dbo.CM_AreaClass.cCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcode(String ccode) {
        this.ccode = ccode == null ? null : ccode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.CM_AreaClass.cName
     *
     * @return the value of dbo.CM_AreaClass.cName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.CM_AreaClass.cName
     *
     * @param cname the value for dbo.CM_AreaClass.cName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.CM_AreaClass.cRemark
     *
     * @return the value of dbo.CM_AreaClass.cRemark
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCremark() {
        return cremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.CM_AreaClass.cRemark
     *
     * @param cremark the value for dbo.CM_AreaClass.cRemark
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCremark(String cremark) {
        this.cremark = cremark == null ? null : cremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.CM_AreaClass.iStatus
     *
     * @return the value of dbo.CM_AreaClass.iStatus
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Short getIstatus() {
        return istatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.CM_AreaClass.iStatus
     *
     * @param istatus the value for dbo.CM_AreaClass.iStatus
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setIstatus(Short istatus) {
        this.istatus = istatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.CM_AreaClass.cTimeStamp
     *
     * @return the value of dbo.CM_AreaClass.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCtimestamp() {
        return ctimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.CM_AreaClass.cTimeStamp
     *
     * @param ctimestamp the value for dbo.CM_AreaClass.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCtimestamp(String ctimestamp) {
        this.ctimestamp = ctimestamp == null ? null : ctimestamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.CM_AreaClass.iLeaf
     *
     * @return the value of dbo.CM_AreaClass.iLeaf
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Short getIleaf() {
        return ileaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.CM_AreaClass.iLeaf
     *
     * @param ileaf the value for dbo.CM_AreaClass.iLeaf
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setIleaf(Short ileaf) {
        this.ileaf = ileaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.CM_AreaClass.cParentID
     *
     * @return the value of dbo.CM_AreaClass.cParentID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCparentid() {
        return cparentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.CM_AreaClass.cParentID
     *
     * @param cparentid the value for dbo.CM_AreaClass.cParentID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCparentid(String cparentid) {
        this.cparentid = cparentid == null ? null : cparentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.CM_AreaClass.iLevel
     *
     * @return the value of dbo.CM_AreaClass.iLevel
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Short getIlevel() {
        return ilevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.CM_AreaClass.iLevel
     *
     * @param ilevel the value for dbo.CM_AreaClass.iLevel
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setIlevel(Short ilevel) {
        this.ilevel = ilevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.CM_AreaClass.cHotCode
     *
     * @return the value of dbo.CM_AreaClass.cHotCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getChotcode() {
        return chotcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.CM_AreaClass.cHotCode
     *
     * @param chotcode the value for dbo.CM_AreaClass.cHotCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setChotcode(String chotcode) {
        this.chotcode = chotcode == null ? null : chotcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.CM_AreaClass.cFullCode
     *
     * @return the value of dbo.CM_AreaClass.cFullCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCfullcode() {
        return cfullcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.CM_AreaClass.cFullCode
     *
     * @param cfullcode the value for dbo.CM_AreaClass.cFullCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCfullcode(String cfullcode) {
        this.cfullcode = cfullcode == null ? null : cfullcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.CM_AreaClass.cInnerCode
     *
     * @return the value of dbo.CM_AreaClass.cInnerCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCinnercode() {
        return cinnercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.CM_AreaClass.cInnerCode
     *
     * @param cinnercode the value for dbo.CM_AreaClass.cInnerCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCinnercode(String cinnercode) {
        this.cinnercode = cinnercode == null ? null : cinnercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.CM_AreaClass.CrmID
     *
     * @return the value of dbo.CM_AreaClass.CrmID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCrmid() {
        return crmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.CM_AreaClass.CrmID
     *
     * @param crmid the value for dbo.CM_AreaClass.CrmID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCrmid(String crmid) {
        this.crmid = crmid == null ? null : crmid.trim();
    }
}