package com.wos.pojo;

import java.util.Date;

public class ChargeType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_ChargeType.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_ChargeType.cCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ccode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_ChargeType.cName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_ChargeType.cPeriodsQty
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Integer cperiodsqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_ChargeType.cPeriodsUnit
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cperiodsunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_ChargeType.cStandard
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Double cstandard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_ChargeType.cCreater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ccreater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_ChargeType.cCreateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date ccreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_ChargeType.cUpdater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cupdater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_ChargeType.cUpdateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date cupdatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_ChargeType.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ctimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_ChargeType.FREECHARGE
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Integer freecharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_ChargeType.cInvoiceName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cinvoicename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_ChargeType.cGUID
     *
     * @return the value of dbo.itsm_service_ChargeType.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCguid() {
        return cguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_ChargeType.cGUID
     *
     * @param cguid the value for dbo.itsm_service_ChargeType.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCguid(String cguid) {
        this.cguid = cguid == null ? null : cguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_ChargeType.cCode
     *
     * @return the value of dbo.itsm_service_ChargeType.cCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCcode() {
        return ccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_ChargeType.cCode
     *
     * @param ccode the value for dbo.itsm_service_ChargeType.cCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcode(String ccode) {
        this.ccode = ccode == null ? null : ccode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_ChargeType.cName
     *
     * @return the value of dbo.itsm_service_ChargeType.cName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_ChargeType.cName
     *
     * @param cname the value for dbo.itsm_service_ChargeType.cName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_ChargeType.cPeriodsQty
     *
     * @return the value of dbo.itsm_service_ChargeType.cPeriodsQty
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Integer getCperiodsqty() {
        return cperiodsqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_ChargeType.cPeriodsQty
     *
     * @param cperiodsqty the value for dbo.itsm_service_ChargeType.cPeriodsQty
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCperiodsqty(Integer cperiodsqty) {
        this.cperiodsqty = cperiodsqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_ChargeType.cPeriodsUnit
     *
     * @return the value of dbo.itsm_service_ChargeType.cPeriodsUnit
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCperiodsunit() {
        return cperiodsunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_ChargeType.cPeriodsUnit
     *
     * @param cperiodsunit the value for dbo.itsm_service_ChargeType.cPeriodsUnit
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCperiodsunit(String cperiodsunit) {
        this.cperiodsunit = cperiodsunit == null ? null : cperiodsunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_ChargeType.cStandard
     *
     * @return the value of dbo.itsm_service_ChargeType.cStandard
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Double getCstandard() {
        return cstandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_ChargeType.cStandard
     *
     * @param cstandard the value for dbo.itsm_service_ChargeType.cStandard
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCstandard(Double cstandard) {
        this.cstandard = cstandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_ChargeType.cCreater
     *
     * @return the value of dbo.itsm_service_ChargeType.cCreater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCcreater() {
        return ccreater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_ChargeType.cCreater
     *
     * @param ccreater the value for dbo.itsm_service_ChargeType.cCreater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcreater(String ccreater) {
        this.ccreater = ccreater == null ? null : ccreater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_ChargeType.cCreateDate
     *
     * @return the value of dbo.itsm_service_ChargeType.cCreateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getCcreatedate() {
        return ccreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_ChargeType.cCreateDate
     *
     * @param ccreatedate the value for dbo.itsm_service_ChargeType.cCreateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcreatedate(Date ccreatedate) {
        this.ccreatedate = ccreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_ChargeType.cUpdater
     *
     * @return the value of dbo.itsm_service_ChargeType.cUpdater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCupdater() {
        return cupdater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_ChargeType.cUpdater
     *
     * @param cupdater the value for dbo.itsm_service_ChargeType.cUpdater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCupdater(String cupdater) {
        this.cupdater = cupdater == null ? null : cupdater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_ChargeType.cUpdateDate
     *
     * @return the value of dbo.itsm_service_ChargeType.cUpdateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getCupdatedate() {
        return cupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_ChargeType.cUpdateDate
     *
     * @param cupdatedate the value for dbo.itsm_service_ChargeType.cUpdateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCupdatedate(Date cupdatedate) {
        this.cupdatedate = cupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_ChargeType.cTimeStamp
     *
     * @return the value of dbo.itsm_service_ChargeType.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCtimestamp() {
        return ctimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_ChargeType.cTimeStamp
     *
     * @param ctimestamp the value for dbo.itsm_service_ChargeType.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCtimestamp(String ctimestamp) {
        this.ctimestamp = ctimestamp == null ? null : ctimestamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_ChargeType.FREECHARGE
     *
     * @return the value of dbo.itsm_service_ChargeType.FREECHARGE
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Integer getFreecharge() {
        return freecharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_ChargeType.FREECHARGE
     *
     * @param freecharge the value for dbo.itsm_service_ChargeType.FREECHARGE
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setFreecharge(Integer freecharge) {
        this.freecharge = freecharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_ChargeType.cInvoiceName
     *
     * @return the value of dbo.itsm_service_ChargeType.cInvoiceName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCinvoicename() {
        return cinvoicename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_ChargeType.cInvoiceName
     *
     * @param cinvoicename the value for dbo.itsm_service_ChargeType.cInvoiceName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCinvoicename(String cinvoicename) {
        this.cinvoicename = cinvoicename == null ? null : cinvoicename.trim();
    }
}