package com.wos.pojo;

import java.util.Date;

public class ConfigInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_Configuration.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_Configuration.cCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ccode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_Configuration.cName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_Configuration.cCreater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ccreater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_Configuration.cCreateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date ccreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_Configuration.cUpdater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cupdater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_Configuration.cUpdateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date cupdatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_Configuration.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ctimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_Configuration.cGUID
     *
     * @return the value of dbo.itsm_service_Configuration.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCguid() {
        return cguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_Configuration.cGUID
     *
     * @param cguid the value for dbo.itsm_service_Configuration.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCguid(String cguid) {
        this.cguid = cguid == null ? null : cguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_Configuration.cCode
     *
     * @return the value of dbo.itsm_service_Configuration.cCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCcode() {
        return ccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_Configuration.cCode
     *
     * @param ccode the value for dbo.itsm_service_Configuration.cCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcode(String ccode) {
        this.ccode = ccode == null ? null : ccode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_Configuration.cName
     *
     * @return the value of dbo.itsm_service_Configuration.cName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_Configuration.cName
     *
     * @param cname the value for dbo.itsm_service_Configuration.cName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_Configuration.cCreater
     *
     * @return the value of dbo.itsm_service_Configuration.cCreater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCcreater() {
        return ccreater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_Configuration.cCreater
     *
     * @param ccreater the value for dbo.itsm_service_Configuration.cCreater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcreater(String ccreater) {
        this.ccreater = ccreater == null ? null : ccreater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_Configuration.cCreateDate
     *
     * @return the value of dbo.itsm_service_Configuration.cCreateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getCcreatedate() {
        return ccreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_Configuration.cCreateDate
     *
     * @param ccreatedate the value for dbo.itsm_service_Configuration.cCreateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcreatedate(Date ccreatedate) {
        this.ccreatedate = ccreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_Configuration.cUpdater
     *
     * @return the value of dbo.itsm_service_Configuration.cUpdater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCupdater() {
        return cupdater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_Configuration.cUpdater
     *
     * @param cupdater the value for dbo.itsm_service_Configuration.cUpdater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCupdater(String cupdater) {
        this.cupdater = cupdater == null ? null : cupdater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_Configuration.cUpdateDate
     *
     * @return the value of dbo.itsm_service_Configuration.cUpdateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getCupdatedate() {
        return cupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_Configuration.cUpdateDate
     *
     * @param cupdatedate the value for dbo.itsm_service_Configuration.cUpdateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCupdatedate(Date cupdatedate) {
        this.cupdatedate = cupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_Configuration.cTimeStamp
     *
     * @return the value of dbo.itsm_service_Configuration.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCtimestamp() {
        return ctimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_Configuration.cTimeStamp
     *
     * @param ctimestamp the value for dbo.itsm_service_Configuration.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCtimestamp(String ctimestamp) {
        this.ctimestamp = ctimestamp == null ? null : ctimestamp.trim();
    }
}