package com.wos.pojo;

public class ConfigExpandInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_ConManagerExpand.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_ConManagerExpand.cMainID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cmainid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_ConManagerExpand.cCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ccode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_ConManagerExpand.cName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_ConManagerExpand.cextid
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cextid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_ConManagerExpand.cid
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_ConManagerExpand.cGUID
     *
     * @return the value of dbo.itsm_service_ConManagerExpand.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCguid() {
        return cguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_ConManagerExpand.cGUID
     *
     * @param cguid the value for dbo.itsm_service_ConManagerExpand.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCguid(String cguid) {
        this.cguid = cguid == null ? null : cguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_ConManagerExpand.cMainID
     *
     * @return the value of dbo.itsm_service_ConManagerExpand.cMainID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCmainid() {
        return cmainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_ConManagerExpand.cMainID
     *
     * @param cmainid the value for dbo.itsm_service_ConManagerExpand.cMainID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCmainid(String cmainid) {
        this.cmainid = cmainid == null ? null : cmainid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_ConManagerExpand.cCode
     *
     * @return the value of dbo.itsm_service_ConManagerExpand.cCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCcode() {
        return ccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_ConManagerExpand.cCode
     *
     * @param ccode the value for dbo.itsm_service_ConManagerExpand.cCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcode(String ccode) {
        this.ccode = ccode == null ? null : ccode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_ConManagerExpand.cName
     *
     * @return the value of dbo.itsm_service_ConManagerExpand.cName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_ConManagerExpand.cName
     *
     * @param cname the value for dbo.itsm_service_ConManagerExpand.cName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_ConManagerExpand.cextid
     *
     * @return the value of dbo.itsm_service_ConManagerExpand.cextid
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCextid() {
        return cextid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_ConManagerExpand.cextid
     *
     * @param cextid the value for dbo.itsm_service_ConManagerExpand.cextid
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCextid(String cextid) {
        this.cextid = cextid == null ? null : cextid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_ConManagerExpand.cid
     *
     * @return the value of dbo.itsm_service_ConManagerExpand.cid
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_ConManagerExpand.cid
     *
     * @param cid the value for dbo.itsm_service_ConManagerExpand.cid
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }
}