package com.wos.pojo;

import java.util.Date;

public class ConfigMgtInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ccode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cCompanyInfoID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ccompanyinfoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cRelationMatID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String crelationmatid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cConfigureUserID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cconfigureuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cIsWriteOff
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ciswriteoff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cInstallDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date cinstalldate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cInstallType
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cinstalltype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cChargeType
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cchargetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cChargeHeader
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cchargeheader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cServiceOverdueDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date cserviceoverduedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cServiceResponse
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cserviceresponse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cVersion
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cIsStauts
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Integer cisstauts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cCreater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ccreater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cCreateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date ccreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cUpdater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cupdater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cUpdateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date cupdatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ctimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cServiceStartDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date cservicestartdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cGuaranteeStartDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date cguaranteestartdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cGuaranteeEndDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date cguaranteeenddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.Barcode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String barcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cIsMain
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Integer cismain;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cGUID
     *
     * @return the value of dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCguid() {
        return cguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cGUID
     *
     * @param cguid the value for dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCguid(String cguid) {
        this.cguid = cguid == null ? null : cguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cCode
     *
     * @return the value of dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCcode() {
        return ccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cCode
     *
     * @param ccode the value for dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcode(String ccode) {
        this.ccode = ccode == null ? null : ccode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cCompanyInfoID
     *
     * @return the value of dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cCompanyInfoID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCcompanyinfoid() {
        return ccompanyinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cCompanyInfoID
     *
     * @param ccompanyinfoid the value for dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cCompanyInfoID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcompanyinfoid(String ccompanyinfoid) {
        this.ccompanyinfoid = ccompanyinfoid == null ? null : ccompanyinfoid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cRelationMatID
     *
     * @return the value of dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cRelationMatID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCrelationmatid() {
        return crelationmatid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cRelationMatID
     *
     * @param crelationmatid the value for dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cRelationMatID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCrelationmatid(String crelationmatid) {
        this.crelationmatid = crelationmatid == null ? null : crelationmatid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cName
     *
     * @return the value of dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cName
     *
     * @param cname the value for dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cConfigureUserID
     *
     * @return the value of dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cConfigureUserID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCconfigureuserid() {
        return cconfigureuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cConfigureUserID
     *
     * @param cconfigureuserid the value for dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cConfigureUserID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCconfigureuserid(String cconfigureuserid) {
        this.cconfigureuserid = cconfigureuserid == null ? null : cconfigureuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cIsWriteOff
     *
     * @return the value of dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cIsWriteOff
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCiswriteoff() {
        return ciswriteoff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cIsWriteOff
     *
     * @param ciswriteoff the value for dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cIsWriteOff
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCiswriteoff(String ciswriteoff) {
        this.ciswriteoff = ciswriteoff == null ? null : ciswriteoff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cInstallDate
     *
     * @return the value of dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cInstallDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getCinstalldate() {
        return cinstalldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cInstallDate
     *
     * @param cinstalldate the value for dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cInstallDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCinstalldate(Date cinstalldate) {
        this.cinstalldate = cinstalldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cInstallType
     *
     * @return the value of dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cInstallType
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCinstalltype() {
        return cinstalltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cInstallType
     *
     * @param cinstalltype the value for dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cInstallType
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCinstalltype(String cinstalltype) {
        this.cinstalltype = cinstalltype == null ? null : cinstalltype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cChargeType
     *
     * @return the value of dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cChargeType
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCchargetype() {
        return cchargetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cChargeType
     *
     * @param cchargetype the value for dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cChargeType
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCchargetype(String cchargetype) {
        this.cchargetype = cchargetype == null ? null : cchargetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cChargeHeader
     *
     * @return the value of dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cChargeHeader
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCchargeheader() {
        return cchargeheader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cChargeHeader
     *
     * @param cchargeheader the value for dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cChargeHeader
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCchargeheader(String cchargeheader) {
        this.cchargeheader = cchargeheader == null ? null : cchargeheader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cServiceOverdueDate
     *
     * @return the value of dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cServiceOverdueDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getCserviceoverduedate() {
        return cserviceoverduedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cServiceOverdueDate
     *
     * @param cserviceoverduedate the value for dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cServiceOverdueDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCserviceoverduedate(Date cserviceoverduedate) {
        this.cserviceoverduedate = cserviceoverduedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cServiceResponse
     *
     * @return the value of dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cServiceResponse
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCserviceresponse() {
        return cserviceresponse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cServiceResponse
     *
     * @param cserviceresponse the value for dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cServiceResponse
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCserviceresponse(String cserviceresponse) {
        this.cserviceresponse = cserviceresponse == null ? null : cserviceresponse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cVersion
     *
     * @return the value of dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cVersion
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCversion() {
        return cversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cVersion
     *
     * @param cversion the value for dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cVersion
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCversion(String cversion) {
        this.cversion = cversion == null ? null : cversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cIsStauts
     *
     * @return the value of dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cIsStauts
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Integer getCisstauts() {
        return cisstauts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cIsStauts
     *
     * @param cisstauts the value for dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cIsStauts
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCisstauts(Integer cisstauts) {
        this.cisstauts = cisstauts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cCreater
     *
     * @return the value of dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cCreater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCcreater() {
        return ccreater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cCreater
     *
     * @param ccreater the value for dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cCreater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcreater(String ccreater) {
        this.ccreater = ccreater == null ? null : ccreater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cCreateDate
     *
     * @return the value of dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cCreateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getCcreatedate() {
        return ccreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cCreateDate
     *
     * @param ccreatedate the value for dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cCreateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcreatedate(Date ccreatedate) {
        this.ccreatedate = ccreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cUpdater
     *
     * @return the value of dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cUpdater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCupdater() {
        return cupdater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cUpdater
     *
     * @param cupdater the value for dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cUpdater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCupdater(String cupdater) {
        this.cupdater = cupdater == null ? null : cupdater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cUpdateDate
     *
     * @return the value of dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cUpdateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getCupdatedate() {
        return cupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cUpdateDate
     *
     * @param cupdatedate the value for dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cUpdateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCupdatedate(Date cupdatedate) {
        this.cupdatedate = cupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cTimeStamp
     *
     * @return the value of dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCtimestamp() {
        return ctimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cTimeStamp
     *
     * @param ctimestamp the value for dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCtimestamp(String ctimestamp) {
        this.ctimestamp = ctimestamp == null ? null : ctimestamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cServiceStartDate
     *
     * @return the value of dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cServiceStartDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getCservicestartdate() {
        return cservicestartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cServiceStartDate
     *
     * @param cservicestartdate the value for dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cServiceStartDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCservicestartdate(Date cservicestartdate) {
        this.cservicestartdate = cservicestartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cGuaranteeStartDate
     *
     * @return the value of dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cGuaranteeStartDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getCguaranteestartdate() {
        return cguaranteestartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cGuaranteeStartDate
     *
     * @param cguaranteestartdate the value for dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cGuaranteeStartDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCguaranteestartdate(Date cguaranteestartdate) {
        this.cguaranteestartdate = cguaranteestartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cGuaranteeEndDate
     *
     * @return the value of dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cGuaranteeEndDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getCguaranteeenddate() {
        return cguaranteeenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cGuaranteeEndDate
     *
     * @param cguaranteeenddate the value for dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cGuaranteeEndDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCguaranteeenddate(Date cguaranteeenddate) {
        this.cguaranteeenddate = cguaranteeenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.Barcode
     *
     * @return the value of dbo.ITSM_SERVICE_CONFIGUREMANAGEME.Barcode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.Barcode
     *
     * @param barcode the value for dbo.ITSM_SERVICE_CONFIGUREMANAGEME.Barcode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode == null ? null : barcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cIsMain
     *
     * @return the value of dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cIsMain
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Integer getCismain() {
        return cismain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cIsMain
     *
     * @param cismain the value for dbo.ITSM_SERVICE_CONFIGUREMANAGEME.cIsMain
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCismain(Integer cismain) {
        this.cismain = cismain;
    }
}