package com.wos.pojo;

import java.util.Date;

public class ContactInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ccode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cNativePlace
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cnativeplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cWorkLife
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cworklife;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cPhoto
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cphoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cStature
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Integer cstature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cMaritalStatus
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Integer cmaritalstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cNationality
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cnationality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cHighestEducation
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String chighesteducation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cSex
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Integer csex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cAge
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Integer cage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cPhone1
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cphone1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cPhone2
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cphone2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cPhone3
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cphone3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cPhone4
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cphone4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cPhone5
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cphone5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cTel1
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ctel1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cTel2
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ctel2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cTel3
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ctel3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cTel4
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ctel4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cTel5
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ctel5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cProfessionalGuid
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cprofessionalguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cAdress
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cadress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cBirthDay
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date cbirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cIDCard
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cidcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cEmail
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cQQ
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cqq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cMemberShipCard
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cmembershipcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cBoss
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cboss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cCreater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ccreater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cCreateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date ccreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cUpdater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cupdater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cUpdateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date cupdatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ctimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.StudentID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String studentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_Contact.CrmID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String crmid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cGUID
     *
     * @return the value of dbo.itsm_base_Contact.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCguid() {
        return cguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cGUID
     *
     * @param cguid the value for dbo.itsm_base_Contact.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCguid(String cguid) {
        this.cguid = cguid == null ? null : cguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cCode
     *
     * @return the value of dbo.itsm_base_Contact.cCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCcode() {
        return ccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cCode
     *
     * @param ccode the value for dbo.itsm_base_Contact.cCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcode(String ccode) {
        this.ccode = ccode == null ? null : ccode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cName
     *
     * @return the value of dbo.itsm_base_Contact.cName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cName
     *
     * @param cname the value for dbo.itsm_base_Contact.cName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cNativePlace
     *
     * @return the value of dbo.itsm_base_Contact.cNativePlace
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCnativeplace() {
        return cnativeplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cNativePlace
     *
     * @param cnativeplace the value for dbo.itsm_base_Contact.cNativePlace
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCnativeplace(String cnativeplace) {
        this.cnativeplace = cnativeplace == null ? null : cnativeplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cWorkLife
     *
     * @return the value of dbo.itsm_base_Contact.cWorkLife
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCworklife() {
        return cworklife;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cWorkLife
     *
     * @param cworklife the value for dbo.itsm_base_Contact.cWorkLife
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCworklife(String cworklife) {
        this.cworklife = cworklife == null ? null : cworklife.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cPhoto
     *
     * @return the value of dbo.itsm_base_Contact.cPhoto
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCphoto() {
        return cphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cPhoto
     *
     * @param cphoto the value for dbo.itsm_base_Contact.cPhoto
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCphoto(String cphoto) {
        this.cphoto = cphoto == null ? null : cphoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cStature
     *
     * @return the value of dbo.itsm_base_Contact.cStature
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Integer getCstature() {
        return cstature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cStature
     *
     * @param cstature the value for dbo.itsm_base_Contact.cStature
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCstature(Integer cstature) {
        this.cstature = cstature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cMaritalStatus
     *
     * @return the value of dbo.itsm_base_Contact.cMaritalStatus
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Integer getCmaritalstatus() {
        return cmaritalstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cMaritalStatus
     *
     * @param cmaritalstatus the value for dbo.itsm_base_Contact.cMaritalStatus
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCmaritalstatus(Integer cmaritalstatus) {
        this.cmaritalstatus = cmaritalstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cNationality
     *
     * @return the value of dbo.itsm_base_Contact.cNationality
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCnationality() {
        return cnationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cNationality
     *
     * @param cnationality the value for dbo.itsm_base_Contact.cNationality
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCnationality(String cnationality) {
        this.cnationality = cnationality == null ? null : cnationality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cHighestEducation
     *
     * @return the value of dbo.itsm_base_Contact.cHighestEducation
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getChighesteducation() {
        return chighesteducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cHighestEducation
     *
     * @param chighesteducation the value for dbo.itsm_base_Contact.cHighestEducation
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setChighesteducation(String chighesteducation) {
        this.chighesteducation = chighesteducation == null ? null : chighesteducation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cSex
     *
     * @return the value of dbo.itsm_base_Contact.cSex
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Integer getCsex() {
        return csex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cSex
     *
     * @param csex the value for dbo.itsm_base_Contact.cSex
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCsex(Integer csex) {
        this.csex = csex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cAge
     *
     * @return the value of dbo.itsm_base_Contact.cAge
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Integer getCage() {
        return cage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cAge
     *
     * @param cage the value for dbo.itsm_base_Contact.cAge
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCage(Integer cage) {
        this.cage = cage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cPhone1
     *
     * @return the value of dbo.itsm_base_Contact.cPhone1
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCphone1() {
        return cphone1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cPhone1
     *
     * @param cphone1 the value for dbo.itsm_base_Contact.cPhone1
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCphone1(String cphone1) {
        this.cphone1 = cphone1 == null ? null : cphone1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cPhone2
     *
     * @return the value of dbo.itsm_base_Contact.cPhone2
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCphone2() {
        return cphone2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cPhone2
     *
     * @param cphone2 the value for dbo.itsm_base_Contact.cPhone2
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCphone2(String cphone2) {
        this.cphone2 = cphone2 == null ? null : cphone2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cPhone3
     *
     * @return the value of dbo.itsm_base_Contact.cPhone3
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCphone3() {
        return cphone3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cPhone3
     *
     * @param cphone3 the value for dbo.itsm_base_Contact.cPhone3
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCphone3(String cphone3) {
        this.cphone3 = cphone3 == null ? null : cphone3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cPhone4
     *
     * @return the value of dbo.itsm_base_Contact.cPhone4
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCphone4() {
        return cphone4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cPhone4
     *
     * @param cphone4 the value for dbo.itsm_base_Contact.cPhone4
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCphone4(String cphone4) {
        this.cphone4 = cphone4 == null ? null : cphone4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cPhone5
     *
     * @return the value of dbo.itsm_base_Contact.cPhone5
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCphone5() {
        return cphone5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cPhone5
     *
     * @param cphone5 the value for dbo.itsm_base_Contact.cPhone5
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCphone5(String cphone5) {
        this.cphone5 = cphone5 == null ? null : cphone5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cTel1
     *
     * @return the value of dbo.itsm_base_Contact.cTel1
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCtel1() {
        return ctel1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cTel1
     *
     * @param ctel1 the value for dbo.itsm_base_Contact.cTel1
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCtel1(String ctel1) {
        this.ctel1 = ctel1 == null ? null : ctel1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cTel2
     *
     * @return the value of dbo.itsm_base_Contact.cTel2
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCtel2() {
        return ctel2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cTel2
     *
     * @param ctel2 the value for dbo.itsm_base_Contact.cTel2
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCtel2(String ctel2) {
        this.ctel2 = ctel2 == null ? null : ctel2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cTel3
     *
     * @return the value of dbo.itsm_base_Contact.cTel3
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCtel3() {
        return ctel3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cTel3
     *
     * @param ctel3 the value for dbo.itsm_base_Contact.cTel3
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCtel3(String ctel3) {
        this.ctel3 = ctel3 == null ? null : ctel3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cTel4
     *
     * @return the value of dbo.itsm_base_Contact.cTel4
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCtel4() {
        return ctel4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cTel4
     *
     * @param ctel4 the value for dbo.itsm_base_Contact.cTel4
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCtel4(String ctel4) {
        this.ctel4 = ctel4 == null ? null : ctel4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cTel5
     *
     * @return the value of dbo.itsm_base_Contact.cTel5
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCtel5() {
        return ctel5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cTel5
     *
     * @param ctel5 the value for dbo.itsm_base_Contact.cTel5
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCtel5(String ctel5) {
        this.ctel5 = ctel5 == null ? null : ctel5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cProfessionalGuid
     *
     * @return the value of dbo.itsm_base_Contact.cProfessionalGuid
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCprofessionalguid() {
        return cprofessionalguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cProfessionalGuid
     *
     * @param cprofessionalguid the value for dbo.itsm_base_Contact.cProfessionalGuid
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCprofessionalguid(String cprofessionalguid) {
        this.cprofessionalguid = cprofessionalguid == null ? null : cprofessionalguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cAdress
     *
     * @return the value of dbo.itsm_base_Contact.cAdress
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCadress() {
        return cadress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cAdress
     *
     * @param cadress the value for dbo.itsm_base_Contact.cAdress
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCadress(String cadress) {
        this.cadress = cadress == null ? null : cadress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cBirthDay
     *
     * @return the value of dbo.itsm_base_Contact.cBirthDay
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getCbirthday() {
        return cbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cBirthDay
     *
     * @param cbirthday the value for dbo.itsm_base_Contact.cBirthDay
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCbirthday(Date cbirthday) {
        this.cbirthday = cbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cIDCard
     *
     * @return the value of dbo.itsm_base_Contact.cIDCard
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCidcard() {
        return cidcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cIDCard
     *
     * @param cidcard the value for dbo.itsm_base_Contact.cIDCard
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCidcard(String cidcard) {
        this.cidcard = cidcard == null ? null : cidcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cEmail
     *
     * @return the value of dbo.itsm_base_Contact.cEmail
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCemail() {
        return cemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cEmail
     *
     * @param cemail the value for dbo.itsm_base_Contact.cEmail
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCemail(String cemail) {
        this.cemail = cemail == null ? null : cemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cQQ
     *
     * @return the value of dbo.itsm_base_Contact.cQQ
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCqq() {
        return cqq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cQQ
     *
     * @param cqq the value for dbo.itsm_base_Contact.cQQ
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCqq(String cqq) {
        this.cqq = cqq == null ? null : cqq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cMemberShipCard
     *
     * @return the value of dbo.itsm_base_Contact.cMemberShipCard
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCmembershipcard() {
        return cmembershipcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cMemberShipCard
     *
     * @param cmembershipcard the value for dbo.itsm_base_Contact.cMemberShipCard
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCmembershipcard(String cmembershipcard) {
        this.cmembershipcard = cmembershipcard == null ? null : cmembershipcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cBoss
     *
     * @return the value of dbo.itsm_base_Contact.cBoss
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCboss() {
        return cboss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cBoss
     *
     * @param cboss the value for dbo.itsm_base_Contact.cBoss
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCboss(String cboss) {
        this.cboss = cboss == null ? null : cboss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cCreater
     *
     * @return the value of dbo.itsm_base_Contact.cCreater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCcreater() {
        return ccreater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cCreater
     *
     * @param ccreater the value for dbo.itsm_base_Contact.cCreater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcreater(String ccreater) {
        this.ccreater = ccreater == null ? null : ccreater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cCreateDate
     *
     * @return the value of dbo.itsm_base_Contact.cCreateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getCcreatedate() {
        return ccreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cCreateDate
     *
     * @param ccreatedate the value for dbo.itsm_base_Contact.cCreateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcreatedate(Date ccreatedate) {
        this.ccreatedate = ccreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cUpdater
     *
     * @return the value of dbo.itsm_base_Contact.cUpdater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCupdater() {
        return cupdater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cUpdater
     *
     * @param cupdater the value for dbo.itsm_base_Contact.cUpdater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCupdater(String cupdater) {
        this.cupdater = cupdater == null ? null : cupdater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cUpdateDate
     *
     * @return the value of dbo.itsm_base_Contact.cUpdateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getCupdatedate() {
        return cupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cUpdateDate
     *
     * @param cupdatedate the value for dbo.itsm_base_Contact.cUpdateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCupdatedate(Date cupdatedate) {
        this.cupdatedate = cupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.cTimeStamp
     *
     * @return the value of dbo.itsm_base_Contact.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCtimestamp() {
        return ctimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.cTimeStamp
     *
     * @param ctimestamp the value for dbo.itsm_base_Contact.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCtimestamp(String ctimestamp) {
        this.ctimestamp = ctimestamp == null ? null : ctimestamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.StudentID
     *
     * @return the value of dbo.itsm_base_Contact.StudentID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.StudentID
     *
     * @param studentid the value for dbo.itsm_base_Contact.StudentID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setStudentid(String studentid) {
        this.studentid = studentid == null ? null : studentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_Contact.CrmID
     *
     * @return the value of dbo.itsm_base_Contact.CrmID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCrmid() {
        return crmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_Contact.CrmID
     *
     * @param crmid the value for dbo.itsm_base_Contact.CrmID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCrmid(String crmid) {
        this.crmid = crmid == null ? null : crmid.trim();
    }
}