package com.wos.pojo;

import java.util.Date;

public class employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.cCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ccode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.cName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.cSName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String csname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.cDeptGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cdeptguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ctimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.iStatus
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Short istatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.iLeaf
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Short ileaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.cParentID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cparentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.iSex
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String isex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.dJoinWorkdate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date djoinworkdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.cJoinSysdate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date cjoinsysdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.cIDNumber
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cidnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.iForeigner
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Short iforeigner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.iStopPayment
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Short istoppayment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.iDimission
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Short idimission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.cDimissionDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date cdimissiondate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.iIsDeleted
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Short iisdeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.cEmail
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.cMobile
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cmobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.cOfficePhone
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cofficephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.cEmployeeTypeGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cemployeetypeguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.cHotCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String chotcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.ccompguid
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ccompguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.cGroupGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cgroupguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.cInsurance
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cinsurance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.cPosition
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cposition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.iEducation
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Short ieducation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.iPolitical
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Short ipolitical;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.dBirthday
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date dbirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.dStartDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date dstartdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.dEndDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date denddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.cHomeAddress
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String chomeaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.cSummy
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String csummy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.cHousingFund
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String chousingfund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.cSpare
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cspare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.cm_employee.CrmID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String crmid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.cGUID
     *
     * @return the value of dbo.cm_employee.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCguid() {
        return cguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.cGUID
     *
     * @param cguid the value for dbo.cm_employee.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCguid(String cguid) {
        this.cguid = cguid == null ? null : cguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.cCode
     *
     * @return the value of dbo.cm_employee.cCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCcode() {
        return ccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.cCode
     *
     * @param ccode the value for dbo.cm_employee.cCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcode(String ccode) {
        this.ccode = ccode == null ? null : ccode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.cName
     *
     * @return the value of dbo.cm_employee.cName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.cName
     *
     * @param cname the value for dbo.cm_employee.cName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.cSName
     *
     * @return the value of dbo.cm_employee.cSName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCsname() {
        return csname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.cSName
     *
     * @param csname the value for dbo.cm_employee.cSName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCsname(String csname) {
        this.csname = csname == null ? null : csname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.cDeptGUID
     *
     * @return the value of dbo.cm_employee.cDeptGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCdeptguid() {
        return cdeptguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.cDeptGUID
     *
     * @param cdeptguid the value for dbo.cm_employee.cDeptGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCdeptguid(String cdeptguid) {
        this.cdeptguid = cdeptguid == null ? null : cdeptguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.cTimeStamp
     *
     * @return the value of dbo.cm_employee.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCtimestamp() {
        return ctimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.cTimeStamp
     *
     * @param ctimestamp the value for dbo.cm_employee.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCtimestamp(String ctimestamp) {
        this.ctimestamp = ctimestamp == null ? null : ctimestamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.iStatus
     *
     * @return the value of dbo.cm_employee.iStatus
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Short getIstatus() {
        return istatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.iStatus
     *
     * @param istatus the value for dbo.cm_employee.iStatus
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setIstatus(Short istatus) {
        this.istatus = istatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.iLeaf
     *
     * @return the value of dbo.cm_employee.iLeaf
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Short getIleaf() {
        return ileaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.iLeaf
     *
     * @param ileaf the value for dbo.cm_employee.iLeaf
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setIleaf(Short ileaf) {
        this.ileaf = ileaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.cParentID
     *
     * @return the value of dbo.cm_employee.cParentID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCparentid() {
        return cparentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.cParentID
     *
     * @param cparentid the value for dbo.cm_employee.cParentID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCparentid(String cparentid) {
        this.cparentid = cparentid == null ? null : cparentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.iSex
     *
     * @return the value of dbo.cm_employee.iSex
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getIsex() {
        return isex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.iSex
     *
     * @param isex the value for dbo.cm_employee.iSex
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setIsex(String isex) {
        this.isex = isex == null ? null : isex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.dJoinWorkdate
     *
     * @return the value of dbo.cm_employee.dJoinWorkdate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getDjoinworkdate() {
        return djoinworkdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.dJoinWorkdate
     *
     * @param djoinworkdate the value for dbo.cm_employee.dJoinWorkdate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setDjoinworkdate(Date djoinworkdate) {
        this.djoinworkdate = djoinworkdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.cJoinSysdate
     *
     * @return the value of dbo.cm_employee.cJoinSysdate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getCjoinsysdate() {
        return cjoinsysdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.cJoinSysdate
     *
     * @param cjoinsysdate the value for dbo.cm_employee.cJoinSysdate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCjoinsysdate(Date cjoinsysdate) {
        this.cjoinsysdate = cjoinsysdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.cIDNumber
     *
     * @return the value of dbo.cm_employee.cIDNumber
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCidnumber() {
        return cidnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.cIDNumber
     *
     * @param cidnumber the value for dbo.cm_employee.cIDNumber
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCidnumber(String cidnumber) {
        this.cidnumber = cidnumber == null ? null : cidnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.iForeigner
     *
     * @return the value of dbo.cm_employee.iForeigner
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Short getIforeigner() {
        return iforeigner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.iForeigner
     *
     * @param iforeigner the value for dbo.cm_employee.iForeigner
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setIforeigner(Short iforeigner) {
        this.iforeigner = iforeigner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.iStopPayment
     *
     * @return the value of dbo.cm_employee.iStopPayment
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Short getIstoppayment() {
        return istoppayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.iStopPayment
     *
     * @param istoppayment the value for dbo.cm_employee.iStopPayment
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setIstoppayment(Short istoppayment) {
        this.istoppayment = istoppayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.iDimission
     *
     * @return the value of dbo.cm_employee.iDimission
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Short getIdimission() {
        return idimission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.iDimission
     *
     * @param idimission the value for dbo.cm_employee.iDimission
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setIdimission(Short idimission) {
        this.idimission = idimission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.cDimissionDate
     *
     * @return the value of dbo.cm_employee.cDimissionDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getCdimissiondate() {
        return cdimissiondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.cDimissionDate
     *
     * @param cdimissiondate the value for dbo.cm_employee.cDimissionDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCdimissiondate(Date cdimissiondate) {
        this.cdimissiondate = cdimissiondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.iIsDeleted
     *
     * @return the value of dbo.cm_employee.iIsDeleted
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Short getIisdeleted() {
        return iisdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.iIsDeleted
     *
     * @param iisdeleted the value for dbo.cm_employee.iIsDeleted
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setIisdeleted(Short iisdeleted) {
        this.iisdeleted = iisdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.cEmail
     *
     * @return the value of dbo.cm_employee.cEmail
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCemail() {
        return cemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.cEmail
     *
     * @param cemail the value for dbo.cm_employee.cEmail
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCemail(String cemail) {
        this.cemail = cemail == null ? null : cemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.cMobile
     *
     * @return the value of dbo.cm_employee.cMobile
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCmobile() {
        return cmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.cMobile
     *
     * @param cmobile the value for dbo.cm_employee.cMobile
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCmobile(String cmobile) {
        this.cmobile = cmobile == null ? null : cmobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.cOfficePhone
     *
     * @return the value of dbo.cm_employee.cOfficePhone
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCofficephone() {
        return cofficephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.cOfficePhone
     *
     * @param cofficephone the value for dbo.cm_employee.cOfficePhone
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCofficephone(String cofficephone) {
        this.cofficephone = cofficephone == null ? null : cofficephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.cEmployeeTypeGUID
     *
     * @return the value of dbo.cm_employee.cEmployeeTypeGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCemployeetypeguid() {
        return cemployeetypeguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.cEmployeeTypeGUID
     *
     * @param cemployeetypeguid the value for dbo.cm_employee.cEmployeeTypeGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCemployeetypeguid(String cemployeetypeguid) {
        this.cemployeetypeguid = cemployeetypeguid == null ? null : cemployeetypeguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.cHotCode
     *
     * @return the value of dbo.cm_employee.cHotCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getChotcode() {
        return chotcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.cHotCode
     *
     * @param chotcode the value for dbo.cm_employee.cHotCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setChotcode(String chotcode) {
        this.chotcode = chotcode == null ? null : chotcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.ccompguid
     *
     * @return the value of dbo.cm_employee.ccompguid
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCcompguid() {
        return ccompguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.ccompguid
     *
     * @param ccompguid the value for dbo.cm_employee.ccompguid
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcompguid(String ccompguid) {
        this.ccompguid = ccompguid == null ? null : ccompguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.cGroupGUID
     *
     * @return the value of dbo.cm_employee.cGroupGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCgroupguid() {
        return cgroupguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.cGroupGUID
     *
     * @param cgroupguid the value for dbo.cm_employee.cGroupGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCgroupguid(String cgroupguid) {
        this.cgroupguid = cgroupguid == null ? null : cgroupguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.cInsurance
     *
     * @return the value of dbo.cm_employee.cInsurance
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCinsurance() {
        return cinsurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.cInsurance
     *
     * @param cinsurance the value for dbo.cm_employee.cInsurance
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCinsurance(String cinsurance) {
        this.cinsurance = cinsurance == null ? null : cinsurance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.cPosition
     *
     * @return the value of dbo.cm_employee.cPosition
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCposition() {
        return cposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.cPosition
     *
     * @param cposition the value for dbo.cm_employee.cPosition
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCposition(String cposition) {
        this.cposition = cposition == null ? null : cposition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.iEducation
     *
     * @return the value of dbo.cm_employee.iEducation
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Short getIeducation() {
        return ieducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.iEducation
     *
     * @param ieducation the value for dbo.cm_employee.iEducation
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setIeducation(Short ieducation) {
        this.ieducation = ieducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.iPolitical
     *
     * @return the value of dbo.cm_employee.iPolitical
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Short getIpolitical() {
        return ipolitical;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.iPolitical
     *
     * @param ipolitical the value for dbo.cm_employee.iPolitical
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setIpolitical(Short ipolitical) {
        this.ipolitical = ipolitical;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.dBirthday
     *
     * @return the value of dbo.cm_employee.dBirthday
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getDbirthday() {
        return dbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.dBirthday
     *
     * @param dbirthday the value for dbo.cm_employee.dBirthday
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setDbirthday(Date dbirthday) {
        this.dbirthday = dbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.dStartDate
     *
     * @return the value of dbo.cm_employee.dStartDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getDstartdate() {
        return dstartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.dStartDate
     *
     * @param dstartdate the value for dbo.cm_employee.dStartDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setDstartdate(Date dstartdate) {
        this.dstartdate = dstartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.dEndDate
     *
     * @return the value of dbo.cm_employee.dEndDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getDenddate() {
        return denddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.dEndDate
     *
     * @param denddate the value for dbo.cm_employee.dEndDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setDenddate(Date denddate) {
        this.denddate = denddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.cHomeAddress
     *
     * @return the value of dbo.cm_employee.cHomeAddress
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getChomeaddress() {
        return chomeaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.cHomeAddress
     *
     * @param chomeaddress the value for dbo.cm_employee.cHomeAddress
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setChomeaddress(String chomeaddress) {
        this.chomeaddress = chomeaddress == null ? null : chomeaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.cSummy
     *
     * @return the value of dbo.cm_employee.cSummy
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCsummy() {
        return csummy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.cSummy
     *
     * @param csummy the value for dbo.cm_employee.cSummy
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCsummy(String csummy) {
        this.csummy = csummy == null ? null : csummy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.cHousingFund
     *
     * @return the value of dbo.cm_employee.cHousingFund
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getChousingfund() {
        return chousingfund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.cHousingFund
     *
     * @param chousingfund the value for dbo.cm_employee.cHousingFund
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setChousingfund(String chousingfund) {
        this.chousingfund = chousingfund == null ? null : chousingfund.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.cSpare
     *
     * @return the value of dbo.cm_employee.cSpare
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCspare() {
        return cspare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.cSpare
     *
     * @param cspare the value for dbo.cm_employee.cSpare
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCspare(String cspare) {
        this.cspare = cspare == null ? null : cspare.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.cm_employee.CrmID
     *
     * @return the value of dbo.cm_employee.CrmID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCrmid() {
        return crmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.cm_employee.CrmID
     *
     * @param crmid the value for dbo.cm_employee.CrmID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCrmid(String crmid) {
        this.crmid = crmid == null ? null : crmid.trim();
    }
}