package com.wos.pojo;

import java.util.Date;

public class EnterpriseAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_EnterpriseAddress.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_EnterpriseAddress.cEnterpriseID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String centerpriseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_EnterpriseAddress.cAdress
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cadress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_EnterpriseAddress.cZipCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String czipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_EnterpriseAddress.cAreaID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String careaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_EnterpriseAddress.cAdressType
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cadresstype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_EnterpriseAddress.cIsValid
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Integer cisvalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_EnterpriseAddress.cCreater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ccreater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_EnterpriseAddress.cCreateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date ccreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_EnterpriseAddress.cUpdater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cupdater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_EnterpriseAddress.cUpdateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date cupdatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_EnterpriseAddress.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ctimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_EnterpriseAddress.Isnew
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Short isnew;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_EnterpriseAddress.CrmID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String crmid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_EnterpriseAddress.cGUID
     *
     * @return the value of dbo.itsm_base_EnterpriseAddress.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCguid() {
        return cguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_EnterpriseAddress.cGUID
     *
     * @param cguid the value for dbo.itsm_base_EnterpriseAddress.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCguid(String cguid) {
        this.cguid = cguid == null ? null : cguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_EnterpriseAddress.cEnterpriseID
     *
     * @return the value of dbo.itsm_base_EnterpriseAddress.cEnterpriseID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCenterpriseid() {
        return centerpriseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_EnterpriseAddress.cEnterpriseID
     *
     * @param centerpriseid the value for dbo.itsm_base_EnterpriseAddress.cEnterpriseID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCenterpriseid(String centerpriseid) {
        this.centerpriseid = centerpriseid == null ? null : centerpriseid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_EnterpriseAddress.cAdress
     *
     * @return the value of dbo.itsm_base_EnterpriseAddress.cAdress
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCadress() {
        return cadress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_EnterpriseAddress.cAdress
     *
     * @param cadress the value for dbo.itsm_base_EnterpriseAddress.cAdress
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCadress(String cadress) {
        this.cadress = cadress == null ? null : cadress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_EnterpriseAddress.cZipCode
     *
     * @return the value of dbo.itsm_base_EnterpriseAddress.cZipCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCzipcode() {
        return czipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_EnterpriseAddress.cZipCode
     *
     * @param czipcode the value for dbo.itsm_base_EnterpriseAddress.cZipCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCzipcode(String czipcode) {
        this.czipcode = czipcode == null ? null : czipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_EnterpriseAddress.cAreaID
     *
     * @return the value of dbo.itsm_base_EnterpriseAddress.cAreaID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCareaid() {
        return careaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_EnterpriseAddress.cAreaID
     *
     * @param careaid the value for dbo.itsm_base_EnterpriseAddress.cAreaID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCareaid(String careaid) {
        this.careaid = careaid == null ? null : careaid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_EnterpriseAddress.cAdressType
     *
     * @return the value of dbo.itsm_base_EnterpriseAddress.cAdressType
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCadresstype() {
        return cadresstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_EnterpriseAddress.cAdressType
     *
     * @param cadresstype the value for dbo.itsm_base_EnterpriseAddress.cAdressType
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCadresstype(String cadresstype) {
        this.cadresstype = cadresstype == null ? null : cadresstype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_EnterpriseAddress.cIsValid
     *
     * @return the value of dbo.itsm_base_EnterpriseAddress.cIsValid
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Integer getCisvalid() {
        return cisvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_EnterpriseAddress.cIsValid
     *
     * @param cisvalid the value for dbo.itsm_base_EnterpriseAddress.cIsValid
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCisvalid(Integer cisvalid) {
        this.cisvalid = cisvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_EnterpriseAddress.cCreater
     *
     * @return the value of dbo.itsm_base_EnterpriseAddress.cCreater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCcreater() {
        return ccreater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_EnterpriseAddress.cCreater
     *
     * @param ccreater the value for dbo.itsm_base_EnterpriseAddress.cCreater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcreater(String ccreater) {
        this.ccreater = ccreater == null ? null : ccreater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_EnterpriseAddress.cCreateDate
     *
     * @return the value of dbo.itsm_base_EnterpriseAddress.cCreateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getCcreatedate() {
        return ccreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_EnterpriseAddress.cCreateDate
     *
     * @param ccreatedate the value for dbo.itsm_base_EnterpriseAddress.cCreateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcreatedate(Date ccreatedate) {
        this.ccreatedate = ccreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_EnterpriseAddress.cUpdater
     *
     * @return the value of dbo.itsm_base_EnterpriseAddress.cUpdater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCupdater() {
        return cupdater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_EnterpriseAddress.cUpdater
     *
     * @param cupdater the value for dbo.itsm_base_EnterpriseAddress.cUpdater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCupdater(String cupdater) {
        this.cupdater = cupdater == null ? null : cupdater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_EnterpriseAddress.cUpdateDate
     *
     * @return the value of dbo.itsm_base_EnterpriseAddress.cUpdateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getCupdatedate() {
        return cupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_EnterpriseAddress.cUpdateDate
     *
     * @param cupdatedate the value for dbo.itsm_base_EnterpriseAddress.cUpdateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCupdatedate(Date cupdatedate) {
        this.cupdatedate = cupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_EnterpriseAddress.cTimeStamp
     *
     * @return the value of dbo.itsm_base_EnterpriseAddress.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCtimestamp() {
        return ctimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_EnterpriseAddress.cTimeStamp
     *
     * @param ctimestamp the value for dbo.itsm_base_EnterpriseAddress.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCtimestamp(String ctimestamp) {
        this.ctimestamp = ctimestamp == null ? null : ctimestamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_EnterpriseAddress.Isnew
     *
     * @return the value of dbo.itsm_base_EnterpriseAddress.Isnew
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Short getIsnew() {
        return isnew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_EnterpriseAddress.Isnew
     *
     * @param isnew the value for dbo.itsm_base_EnterpriseAddress.Isnew
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setIsnew(Short isnew) {
        this.isnew = isnew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_EnterpriseAddress.CrmID
     *
     * @return the value of dbo.itsm_base_EnterpriseAddress.CrmID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCrmid() {
        return crmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_EnterpriseAddress.CrmID
     *
     * @param crmid the value for dbo.itsm_base_EnterpriseAddress.CrmID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCrmid(String crmid) {
        this.crmid = crmid == null ? null : crmid.trim();
    }
}