package com.wos.pojo;

import java.util.Date;

public class ExtendedAttribute {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_ExtendedAttribute.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_ExtendedAttribute.cMatID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cmatid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_ExtendedAttribute.cIsInstall
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Integer cisinstall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_ExtendedAttribute.cIsRepair
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Integer cisrepair;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_ExtendedAttribute.cIsChange
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Integer cischange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_ExtendedAttribute.cName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_ExtendedAttribute.cDefault
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cdefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_ExtendedAttribute.cInputMode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cinputmode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_ExtendedAttribute.cValue
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_ExtendedAttribute.cCreater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ccreater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_ExtendedAttribute.cCreateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date ccreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_ExtendedAttribute.cUpdater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cupdater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_ExtendedAttribute.cUpdateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date cupdatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_ExtendedAttribute.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ctimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_ExtendedAttribute.cEmun
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cemun;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_ExtendedAttribute.cEntityId
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String centityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_ExtendedAttribute.cDefutValue
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cdefutvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_ExtendedAttribute.inumber
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Integer inumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_ExtendedAttribute.cGUID
     *
     * @return the value of dbo.itsm_base_ExtendedAttribute.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCguid() {
        return cguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_ExtendedAttribute.cGUID
     *
     * @param cguid the value for dbo.itsm_base_ExtendedAttribute.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCguid(String cguid) {
        this.cguid = cguid == null ? null : cguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_ExtendedAttribute.cMatID
     *
     * @return the value of dbo.itsm_base_ExtendedAttribute.cMatID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCmatid() {
        return cmatid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_ExtendedAttribute.cMatID
     *
     * @param cmatid the value for dbo.itsm_base_ExtendedAttribute.cMatID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCmatid(String cmatid) {
        this.cmatid = cmatid == null ? null : cmatid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_ExtendedAttribute.cIsInstall
     *
     * @return the value of dbo.itsm_base_ExtendedAttribute.cIsInstall
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Integer getCisinstall() {
        return cisinstall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_ExtendedAttribute.cIsInstall
     *
     * @param cisinstall the value for dbo.itsm_base_ExtendedAttribute.cIsInstall
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCisinstall(Integer cisinstall) {
        this.cisinstall = cisinstall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_ExtendedAttribute.cIsRepair
     *
     * @return the value of dbo.itsm_base_ExtendedAttribute.cIsRepair
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Integer getCisrepair() {
        return cisrepair;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_ExtendedAttribute.cIsRepair
     *
     * @param cisrepair the value for dbo.itsm_base_ExtendedAttribute.cIsRepair
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCisrepair(Integer cisrepair) {
        this.cisrepair = cisrepair;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_ExtendedAttribute.cIsChange
     *
     * @return the value of dbo.itsm_base_ExtendedAttribute.cIsChange
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Integer getCischange() {
        return cischange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_ExtendedAttribute.cIsChange
     *
     * @param cischange the value for dbo.itsm_base_ExtendedAttribute.cIsChange
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCischange(Integer cischange) {
        this.cischange = cischange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_ExtendedAttribute.cName
     *
     * @return the value of dbo.itsm_base_ExtendedAttribute.cName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_ExtendedAttribute.cName
     *
     * @param cname the value for dbo.itsm_base_ExtendedAttribute.cName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_ExtendedAttribute.cDefault
     *
     * @return the value of dbo.itsm_base_ExtendedAttribute.cDefault
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCdefault() {
        return cdefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_ExtendedAttribute.cDefault
     *
     * @param cdefault the value for dbo.itsm_base_ExtendedAttribute.cDefault
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCdefault(String cdefault) {
        this.cdefault = cdefault == null ? null : cdefault.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_ExtendedAttribute.cInputMode
     *
     * @return the value of dbo.itsm_base_ExtendedAttribute.cInputMode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCinputmode() {
        return cinputmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_ExtendedAttribute.cInputMode
     *
     * @param cinputmode the value for dbo.itsm_base_ExtendedAttribute.cInputMode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCinputmode(String cinputmode) {
        this.cinputmode = cinputmode == null ? null : cinputmode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_ExtendedAttribute.cValue
     *
     * @return the value of dbo.itsm_base_ExtendedAttribute.cValue
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCvalue() {
        return cvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_ExtendedAttribute.cValue
     *
     * @param cvalue the value for dbo.itsm_base_ExtendedAttribute.cValue
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCvalue(String cvalue) {
        this.cvalue = cvalue == null ? null : cvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_ExtendedAttribute.cCreater
     *
     * @return the value of dbo.itsm_base_ExtendedAttribute.cCreater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCcreater() {
        return ccreater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_ExtendedAttribute.cCreater
     *
     * @param ccreater the value for dbo.itsm_base_ExtendedAttribute.cCreater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcreater(String ccreater) {
        this.ccreater = ccreater == null ? null : ccreater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_ExtendedAttribute.cCreateDate
     *
     * @return the value of dbo.itsm_base_ExtendedAttribute.cCreateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getCcreatedate() {
        return ccreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_ExtendedAttribute.cCreateDate
     *
     * @param ccreatedate the value for dbo.itsm_base_ExtendedAttribute.cCreateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcreatedate(Date ccreatedate) {
        this.ccreatedate = ccreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_ExtendedAttribute.cUpdater
     *
     * @return the value of dbo.itsm_base_ExtendedAttribute.cUpdater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCupdater() {
        return cupdater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_ExtendedAttribute.cUpdater
     *
     * @param cupdater the value for dbo.itsm_base_ExtendedAttribute.cUpdater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCupdater(String cupdater) {
        this.cupdater = cupdater == null ? null : cupdater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_ExtendedAttribute.cUpdateDate
     *
     * @return the value of dbo.itsm_base_ExtendedAttribute.cUpdateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getCupdatedate() {
        return cupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_ExtendedAttribute.cUpdateDate
     *
     * @param cupdatedate the value for dbo.itsm_base_ExtendedAttribute.cUpdateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCupdatedate(Date cupdatedate) {
        this.cupdatedate = cupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_ExtendedAttribute.cTimeStamp
     *
     * @return the value of dbo.itsm_base_ExtendedAttribute.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCtimestamp() {
        return ctimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_ExtendedAttribute.cTimeStamp
     *
     * @param ctimestamp the value for dbo.itsm_base_ExtendedAttribute.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCtimestamp(String ctimestamp) {
        this.ctimestamp = ctimestamp == null ? null : ctimestamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_ExtendedAttribute.cEmun
     *
     * @return the value of dbo.itsm_base_ExtendedAttribute.cEmun
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCemun() {
        return cemun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_ExtendedAttribute.cEmun
     *
     * @param cemun the value for dbo.itsm_base_ExtendedAttribute.cEmun
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCemun(String cemun) {
        this.cemun = cemun == null ? null : cemun.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_ExtendedAttribute.cEntityId
     *
     * @return the value of dbo.itsm_base_ExtendedAttribute.cEntityId
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCentityid() {
        return centityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_ExtendedAttribute.cEntityId
     *
     * @param centityid the value for dbo.itsm_base_ExtendedAttribute.cEntityId
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCentityid(String centityid) {
        this.centityid = centityid == null ? null : centityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_ExtendedAttribute.cDefutValue
     *
     * @return the value of dbo.itsm_base_ExtendedAttribute.cDefutValue
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCdefutvalue() {
        return cdefutvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_ExtendedAttribute.cDefutValue
     *
     * @param cdefutvalue the value for dbo.itsm_base_ExtendedAttribute.cDefutValue
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCdefutvalue(String cdefutvalue) {
        this.cdefutvalue = cdefutvalue == null ? null : cdefutvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_ExtendedAttribute.inumber
     *
     * @return the value of dbo.itsm_base_ExtendedAttribute.inumber
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Integer getInumber() {
        return inumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_ExtendedAttribute.inumber
     *
     * @param inumber the value for dbo.itsm_base_ExtendedAttribute.inumber
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setInumber(Integer inumber) {
        this.inumber = inumber;
    }
}