package com.wos.pojo;

import java.util.List;

public class InstallDocuCofig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocuCofing.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocuCofing.cName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocuCofing.cValue
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocuCofing.cid
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocuCofing.cMainID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cmainid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocuCofing.cextid
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cextid;
    
    private List<EnumerateInfo> enumerateInfos;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocuCofing.cGUID
     *
     * @return the value of dbo.itsm_service_InstallDocuCofing.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCguid() {
        return cguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocuCofing.cGUID
     *
     * @param cguid the value for dbo.itsm_service_InstallDocuCofing.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCguid(String cguid) {
        this.cguid = cguid == null ? null : cguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocuCofing.cName
     *
     * @return the value of dbo.itsm_service_InstallDocuCofing.cName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocuCofing.cName
     *
     * @param cname the value for dbo.itsm_service_InstallDocuCofing.cName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocuCofing.cValue
     *
     * @return the value of dbo.itsm_service_InstallDocuCofing.cValue
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCvalue() {
        return cvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocuCofing.cValue
     *
     * @param cvalue the value for dbo.itsm_service_InstallDocuCofing.cValue
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCvalue(String cvalue) {
        this.cvalue = cvalue == null ? null : cvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocuCofing.cid
     *
     * @return the value of dbo.itsm_service_InstallDocuCofing.cid
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocuCofing.cid
     *
     * @param cid the value for dbo.itsm_service_InstallDocuCofing.cid
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocuCofing.cMainID
     *
     * @return the value of dbo.itsm_service_InstallDocuCofing.cMainID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCmainid() {
        return cmainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocuCofing.cMainID
     *
     * @param cmainid the value for dbo.itsm_service_InstallDocuCofing.cMainID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCmainid(String cmainid) {
        this.cmainid = cmainid == null ? null : cmainid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocuCofing.cextid
     *
     * @return the value of dbo.itsm_service_InstallDocuCofing.cextid
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCextid() {
        return cextid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocuCofing.cextid
     *
     * @param cextid the value for dbo.itsm_service_InstallDocuCofing.cextid
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCextid(String cextid) {
        this.cextid = cextid == null ? null : cextid.trim();
    }

    public List<EnumerateInfo> getEnumerateInfos()
    {
        return enumerateInfos;
    }

    public void setEnumerateInfos(List<EnumerateInfo> enumerateInfos)
    {
        this.enumerateInfos = enumerateInfos;
    }
    
    
}