package com.wos.pojo;

import java.util.Date;

public class InstallTemplate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallTemplate.cGUID
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    private String cguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallTemplate.cCode
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    private String ccode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallTemplate.cName
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallTemplate.cPrintTemplateID
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    private String cprinttemplateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallTemplate.cCreater
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    private String ccreater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallTemplate.cCreateDate
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    private Date ccreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallTemplate.cUpdater
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    private String cupdater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallTemplate.cUpdateDate
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    private Date cupdatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallTemplate.cTimeStamp
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    private String ctimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallTemplate.initial
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    private String initial;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallTemplate.cGUID
     *
     * @return the value of dbo.itsm_service_InstallTemplate.cGUID
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    public String getCguid() {
        return cguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallTemplate.cGUID
     *
     * @param cguid the value for dbo.itsm_service_InstallTemplate.cGUID
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    public void setCguid(String cguid) {
        this.cguid = cguid == null ? null : cguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallTemplate.cCode
     *
     * @return the value of dbo.itsm_service_InstallTemplate.cCode
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    public String getCcode() {
        return ccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallTemplate.cCode
     *
     * @param ccode the value for dbo.itsm_service_InstallTemplate.cCode
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    public void setCcode(String ccode) {
        this.ccode = ccode == null ? null : ccode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallTemplate.cName
     *
     * @return the value of dbo.itsm_service_InstallTemplate.cName
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallTemplate.cName
     *
     * @param cname the value for dbo.itsm_service_InstallTemplate.cName
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallTemplate.cPrintTemplateID
     *
     * @return the value of dbo.itsm_service_InstallTemplate.cPrintTemplateID
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    public String getCprinttemplateid() {
        return cprinttemplateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallTemplate.cPrintTemplateID
     *
     * @param cprinttemplateid the value for dbo.itsm_service_InstallTemplate.cPrintTemplateID
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    public void setCprinttemplateid(String cprinttemplateid) {
        this.cprinttemplateid = cprinttemplateid == null ? null : cprinttemplateid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallTemplate.cCreater
     *
     * @return the value of dbo.itsm_service_InstallTemplate.cCreater
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    public String getCcreater() {
        return ccreater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallTemplate.cCreater
     *
     * @param ccreater the value for dbo.itsm_service_InstallTemplate.cCreater
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    public void setCcreater(String ccreater) {
        this.ccreater = ccreater == null ? null : ccreater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallTemplate.cCreateDate
     *
     * @return the value of dbo.itsm_service_InstallTemplate.cCreateDate
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    public Date getCcreatedate() {
        return ccreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallTemplate.cCreateDate
     *
     * @param ccreatedate the value for dbo.itsm_service_InstallTemplate.cCreateDate
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    public void setCcreatedate(Date ccreatedate) {
        this.ccreatedate = ccreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallTemplate.cUpdater
     *
     * @return the value of dbo.itsm_service_InstallTemplate.cUpdater
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    public String getCupdater() {
        return cupdater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallTemplate.cUpdater
     *
     * @param cupdater the value for dbo.itsm_service_InstallTemplate.cUpdater
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    public void setCupdater(String cupdater) {
        this.cupdater = cupdater == null ? null : cupdater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallTemplate.cUpdateDate
     *
     * @return the value of dbo.itsm_service_InstallTemplate.cUpdateDate
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    public Date getCupdatedate() {
        return cupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallTemplate.cUpdateDate
     *
     * @param cupdatedate the value for dbo.itsm_service_InstallTemplate.cUpdateDate
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    public void setCupdatedate(Date cupdatedate) {
        this.cupdatedate = cupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallTemplate.cTimeStamp
     *
     * @return the value of dbo.itsm_service_InstallTemplate.cTimeStamp
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    public String getCtimestamp() {
        return ctimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallTemplate.cTimeStamp
     *
     * @param ctimestamp the value for dbo.itsm_service_InstallTemplate.cTimeStamp
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    public void setCtimestamp(String ctimestamp) {
        this.ctimestamp = ctimestamp == null ? null : ctimestamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallTemplate.initial
     *
     * @return the value of dbo.itsm_service_InstallTemplate.initial
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    public String getInitial() {
        return initial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallTemplate.initial
     *
     * @param initial the value for dbo.itsm_service_InstallTemplate.initial
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    public void setInitial(String initial) {
        this.initial = initial == null ? null : initial.trim();
    }
}