package com.wos.pojo;

import java.util.Date;

public class InstallDocument {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.cEventID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ceventid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.cCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ccode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.cEnterpriseID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String centerpriseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.cTaxCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ctaxcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.cEnterpriseName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String centerprisename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.cBelongTax
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cbelongtax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.cEnterpriseAdress
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String centerpriseadress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.cEnterpriseDepartment
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String centerprisedepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.cContactID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ccontactid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.cContactName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ccontactname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.cContactTel
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ccontacttel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.cContactPhone
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ccontactphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.cInstallTypeID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cinstalltypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.cInstallDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date cinstalldate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.cInstallResult
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cinstallresult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.cUnsuccessResult
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cunsuccessresult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.cDepartment
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cdepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.cArea
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String carea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.cEmployeeID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cemployeeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.cStatus
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Integer cstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.cCreater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ccreater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.cCreateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date ccreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.cAuditorGuid
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cauditorguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.cAuditTime
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date caudittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.cLastUpdater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String clastupdater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.cLastUpdateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date clastupdatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ctimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.cInstallType
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cinstalltype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.Remarks
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.isAuditingQualified
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Integer isauditingqualified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.isAuditingEffective
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Integer isauditingeffective;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.NoQualifiedReason
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String noqualifiedreason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_InstallDocument.CustomerSignature
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String customersignature;
    
    private EnterpriseBaseInfo enterpriseBaseInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.cGUID
     *
     * @return the value of dbo.itsm_service_InstallDocument.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCguid() {
        return cguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.cGUID
     *
     * @param cguid the value for dbo.itsm_service_InstallDocument.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCguid(String cguid) {
        this.cguid = cguid == null ? null : cguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.cEventID
     *
     * @return the value of dbo.itsm_service_InstallDocument.cEventID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCeventid() {
        return ceventid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.cEventID
     *
     * @param ceventid the value for dbo.itsm_service_InstallDocument.cEventID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCeventid(String ceventid) {
        this.ceventid = ceventid == null ? null : ceventid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.cCode
     *
     * @return the value of dbo.itsm_service_InstallDocument.cCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCcode() {
        return ccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.cCode
     *
     * @param ccode the value for dbo.itsm_service_InstallDocument.cCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcode(String ccode) {
        this.ccode = ccode == null ? null : ccode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.cEnterpriseID
     *
     * @return the value of dbo.itsm_service_InstallDocument.cEnterpriseID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCenterpriseid() {
        return centerpriseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.cEnterpriseID
     *
     * @param centerpriseid the value for dbo.itsm_service_InstallDocument.cEnterpriseID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCenterpriseid(String centerpriseid) {
        this.centerpriseid = centerpriseid == null ? null : centerpriseid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.cTaxCode
     *
     * @return the value of dbo.itsm_service_InstallDocument.cTaxCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCtaxcode() {
        return ctaxcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.cTaxCode
     *
     * @param ctaxcode the value for dbo.itsm_service_InstallDocument.cTaxCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCtaxcode(String ctaxcode) {
        this.ctaxcode = ctaxcode == null ? null : ctaxcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.cEnterpriseName
     *
     * @return the value of dbo.itsm_service_InstallDocument.cEnterpriseName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCenterprisename() {
        return centerprisename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.cEnterpriseName
     *
     * @param centerprisename the value for dbo.itsm_service_InstallDocument.cEnterpriseName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCenterprisename(String centerprisename) {
        this.centerprisename = centerprisename == null ? null : centerprisename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.cBelongTax
     *
     * @return the value of dbo.itsm_service_InstallDocument.cBelongTax
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCbelongtax() {
        return cbelongtax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.cBelongTax
     *
     * @param cbelongtax the value for dbo.itsm_service_InstallDocument.cBelongTax
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCbelongtax(String cbelongtax) {
        this.cbelongtax = cbelongtax == null ? null : cbelongtax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.cEnterpriseAdress
     *
     * @return the value of dbo.itsm_service_InstallDocument.cEnterpriseAdress
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCenterpriseadress() {
        return centerpriseadress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.cEnterpriseAdress
     *
     * @param centerpriseadress the value for dbo.itsm_service_InstallDocument.cEnterpriseAdress
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCenterpriseadress(String centerpriseadress) {
        this.centerpriseadress = centerpriseadress == null ? null : centerpriseadress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.cEnterpriseDepartment
     *
     * @return the value of dbo.itsm_service_InstallDocument.cEnterpriseDepartment
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCenterprisedepartment() {
        return centerprisedepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.cEnterpriseDepartment
     *
     * @param centerprisedepartment the value for dbo.itsm_service_InstallDocument.cEnterpriseDepartment
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCenterprisedepartment(String centerprisedepartment) {
        this.centerprisedepartment = centerprisedepartment == null ? null : centerprisedepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.cContactID
     *
     * @return the value of dbo.itsm_service_InstallDocument.cContactID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCcontactid() {
        return ccontactid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.cContactID
     *
     * @param ccontactid the value for dbo.itsm_service_InstallDocument.cContactID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcontactid(String ccontactid) {
        this.ccontactid = ccontactid == null ? null : ccontactid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.cContactName
     *
     * @return the value of dbo.itsm_service_InstallDocument.cContactName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCcontactname() {
        return ccontactname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.cContactName
     *
     * @param ccontactname the value for dbo.itsm_service_InstallDocument.cContactName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcontactname(String ccontactname) {
        this.ccontactname = ccontactname == null ? null : ccontactname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.cContactTel
     *
     * @return the value of dbo.itsm_service_InstallDocument.cContactTel
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCcontacttel() {
        return ccontacttel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.cContactTel
     *
     * @param ccontacttel the value for dbo.itsm_service_InstallDocument.cContactTel
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcontacttel(String ccontacttel) {
        this.ccontacttel = ccontacttel == null ? null : ccontacttel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.cContactPhone
     *
     * @return the value of dbo.itsm_service_InstallDocument.cContactPhone
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCcontactphone() {
        return ccontactphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.cContactPhone
     *
     * @param ccontactphone the value for dbo.itsm_service_InstallDocument.cContactPhone
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcontactphone(String ccontactphone) {
        this.ccontactphone = ccontactphone == null ? null : ccontactphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.cInstallTypeID
     *
     * @return the value of dbo.itsm_service_InstallDocument.cInstallTypeID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCinstalltypeid() {
        return cinstalltypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.cInstallTypeID
     *
     * @param cinstalltypeid the value for dbo.itsm_service_InstallDocument.cInstallTypeID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCinstalltypeid(String cinstalltypeid) {
        this.cinstalltypeid = cinstalltypeid == null ? null : cinstalltypeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.cInstallDate
     *
     * @return the value of dbo.itsm_service_InstallDocument.cInstallDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getCinstalldate() {
        return cinstalldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.cInstallDate
     *
     * @param cinstalldate the value for dbo.itsm_service_InstallDocument.cInstallDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCinstalldate(Date cinstalldate) {
        this.cinstalldate = cinstalldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.cInstallResult
     *
     * @return the value of dbo.itsm_service_InstallDocument.cInstallResult
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCinstallresult() {
        return cinstallresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.cInstallResult
     *
     * @param cinstallresult the value for dbo.itsm_service_InstallDocument.cInstallResult
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCinstallresult(String cinstallresult) {
        this.cinstallresult = cinstallresult == null ? null : cinstallresult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.cUnsuccessResult
     *
     * @return the value of dbo.itsm_service_InstallDocument.cUnsuccessResult
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCunsuccessresult() {
        return cunsuccessresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.cUnsuccessResult
     *
     * @param cunsuccessresult the value for dbo.itsm_service_InstallDocument.cUnsuccessResult
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCunsuccessresult(String cunsuccessresult) {
        this.cunsuccessresult = cunsuccessresult == null ? null : cunsuccessresult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.cDepartment
     *
     * @return the value of dbo.itsm_service_InstallDocument.cDepartment
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCdepartment() {
        return cdepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.cDepartment
     *
     * @param cdepartment the value for dbo.itsm_service_InstallDocument.cDepartment
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCdepartment(String cdepartment) {
        this.cdepartment = cdepartment == null ? null : cdepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.cArea
     *
     * @return the value of dbo.itsm_service_InstallDocument.cArea
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCarea() {
        return carea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.cArea
     *
     * @param carea the value for dbo.itsm_service_InstallDocument.cArea
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCarea(String carea) {
        this.carea = carea == null ? null : carea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.cEmployeeID
     *
     * @return the value of dbo.itsm_service_InstallDocument.cEmployeeID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCemployeeid() {
        return cemployeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.cEmployeeID
     *
     * @param cemployeeid the value for dbo.itsm_service_InstallDocument.cEmployeeID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCemployeeid(String cemployeeid) {
        this.cemployeeid = cemployeeid == null ? null : cemployeeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.cStatus
     *
     * @return the value of dbo.itsm_service_InstallDocument.cStatus
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Integer getCstatus() {
        return cstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.cStatus
     *
     * @param cstatus the value for dbo.itsm_service_InstallDocument.cStatus
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCstatus(Integer cstatus) {
        this.cstatus = cstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.cCreater
     *
     * @return the value of dbo.itsm_service_InstallDocument.cCreater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCcreater() {
        return ccreater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.cCreater
     *
     * @param ccreater the value for dbo.itsm_service_InstallDocument.cCreater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcreater(String ccreater) {
        this.ccreater = ccreater == null ? null : ccreater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.cCreateDate
     *
     * @return the value of dbo.itsm_service_InstallDocument.cCreateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getCcreatedate() {
        return ccreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.cCreateDate
     *
     * @param ccreatedate the value for dbo.itsm_service_InstallDocument.cCreateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcreatedate(Date ccreatedate) {
        this.ccreatedate = ccreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.cAuditorGuid
     *
     * @return the value of dbo.itsm_service_InstallDocument.cAuditorGuid
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCauditorguid() {
        return cauditorguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.cAuditorGuid
     *
     * @param cauditorguid the value for dbo.itsm_service_InstallDocument.cAuditorGuid
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCauditorguid(String cauditorguid) {
        this.cauditorguid = cauditorguid == null ? null : cauditorguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.cAuditTime
     *
     * @return the value of dbo.itsm_service_InstallDocument.cAuditTime
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getCaudittime() {
        return caudittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.cAuditTime
     *
     * @param caudittime the value for dbo.itsm_service_InstallDocument.cAuditTime
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCaudittime(Date caudittime) {
        this.caudittime = caudittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.cLastUpdater
     *
     * @return the value of dbo.itsm_service_InstallDocument.cLastUpdater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getClastupdater() {
        return clastupdater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.cLastUpdater
     *
     * @param clastupdater the value for dbo.itsm_service_InstallDocument.cLastUpdater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setClastupdater(String clastupdater) {
        this.clastupdater = clastupdater == null ? null : clastupdater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.cLastUpdateDate
     *
     * @return the value of dbo.itsm_service_InstallDocument.cLastUpdateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getClastupdatedate() {
        return clastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.cLastUpdateDate
     *
     * @param clastupdatedate the value for dbo.itsm_service_InstallDocument.cLastUpdateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setClastupdatedate(Date clastupdatedate) {
        this.clastupdatedate = clastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.cTimeStamp
     *
     * @return the value of dbo.itsm_service_InstallDocument.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCtimestamp() {
        return ctimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.cTimeStamp
     *
     * @param ctimestamp the value for dbo.itsm_service_InstallDocument.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCtimestamp(String ctimestamp) {
        this.ctimestamp = ctimestamp == null ? null : ctimestamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.cInstallType
     *
     * @return the value of dbo.itsm_service_InstallDocument.cInstallType
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCinstalltype() {
        return cinstalltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.cInstallType
     *
     * @param cinstalltype the value for dbo.itsm_service_InstallDocument.cInstallType
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCinstalltype(String cinstalltype) {
        this.cinstalltype = cinstalltype == null ? null : cinstalltype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.Remarks
     *
     * @return the value of dbo.itsm_service_InstallDocument.Remarks
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.Remarks
     *
     * @param remarks the value for dbo.itsm_service_InstallDocument.Remarks
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.isAuditingQualified
     *
     * @return the value of dbo.itsm_service_InstallDocument.isAuditingQualified
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Integer getIsauditingqualified() {
        return isauditingqualified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.isAuditingQualified
     *
     * @param isauditingqualified the value for dbo.itsm_service_InstallDocument.isAuditingQualified
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setIsauditingqualified(Integer isauditingqualified) {
        this.isauditingqualified = isauditingqualified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.isAuditingEffective
     *
     * @return the value of dbo.itsm_service_InstallDocument.isAuditingEffective
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Integer getIsauditingeffective() {
        return isauditingeffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.isAuditingEffective
     *
     * @param isauditingeffective the value for dbo.itsm_service_InstallDocument.isAuditingEffective
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setIsauditingeffective(Integer isauditingeffective) {
        this.isauditingeffective = isauditingeffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.NoQualifiedReason
     *
     * @return the value of dbo.itsm_service_InstallDocument.NoQualifiedReason
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getNoqualifiedreason() {
        return noqualifiedreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.NoQualifiedReason
     *
     * @param noqualifiedreason the value for dbo.itsm_service_InstallDocument.NoQualifiedReason
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setNoqualifiedreason(String noqualifiedreason) {
        this.noqualifiedreason = noqualifiedreason == null ? null : noqualifiedreason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_InstallDocument.CustomerSignature
     *
     * @return the value of dbo.itsm_service_InstallDocument.CustomerSignature
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCustomersignature() {
        return customersignature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_InstallDocument.CustomerSignature
     *
     * @param customersignature the value for dbo.itsm_service_InstallDocument.CustomerSignature
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCustomersignature(String customersignature) {
        this.customersignature = customersignature == null ? null : customersignature.trim();
    }

	public EnterpriseBaseInfo getEnterpriseBaseInfo() {
		return enterpriseBaseInfo;
	}

	public void setEnterpriseBaseInfo(EnterpriseBaseInfo enterpriseBaseInfo) {
		this.enterpriseBaseInfo = enterpriseBaseInfo;
	}
    
    
}