package com.wos.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class InstallTemplateExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.itsm_service_InstallTemplate
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.itsm_service_InstallTemplate
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.itsm_service_InstallTemplate
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_InstallTemplate
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    public InstallTemplateExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_InstallTemplate
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_InstallTemplate
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_InstallTemplate
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_InstallTemplate
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_InstallTemplate
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_InstallTemplate
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_InstallTemplate
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_InstallTemplate
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_InstallTemplate
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.itsm_service_InstallTemplate
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.itsm_service_InstallTemplate
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCguidIsNull() {
            addCriterion("cGUID is null");
            return (Criteria) this;
        }

        public Criteria andCguidIsNotNull() {
            addCriterion("cGUID is not null");
            return (Criteria) this;
        }

        public Criteria andCguidEqualTo(String value) {
            addCriterion("cGUID =", value, "cguid");
            return (Criteria) this;
        }

        public Criteria andCguidNotEqualTo(String value) {
            addCriterion("cGUID <>", value, "cguid");
            return (Criteria) this;
        }

        public Criteria andCguidGreaterThan(String value) {
            addCriterion("cGUID >", value, "cguid");
            return (Criteria) this;
        }

        public Criteria andCguidGreaterThanOrEqualTo(String value) {
            addCriterion("cGUID >=", value, "cguid");
            return (Criteria) this;
        }

        public Criteria andCguidLessThan(String value) {
            addCriterion("cGUID <", value, "cguid");
            return (Criteria) this;
        }

        public Criteria andCguidLessThanOrEqualTo(String value) {
            addCriterion("cGUID <=", value, "cguid");
            return (Criteria) this;
        }

        public Criteria andCguidLike(String value) {
            addCriterion("cGUID like", value, "cguid");
            return (Criteria) this;
        }

        public Criteria andCguidNotLike(String value) {
            addCriterion("cGUID not like", value, "cguid");
            return (Criteria) this;
        }

        public Criteria andCguidIn(List<String> values) {
            addCriterion("cGUID in", values, "cguid");
            return (Criteria) this;
        }

        public Criteria andCguidNotIn(List<String> values) {
            addCriterion("cGUID not in", values, "cguid");
            return (Criteria) this;
        }

        public Criteria andCguidBetween(String value1, String value2) {
            addCriterion("cGUID between", value1, value2, "cguid");
            return (Criteria) this;
        }

        public Criteria andCguidNotBetween(String value1, String value2) {
            addCriterion("cGUID not between", value1, value2, "cguid");
            return (Criteria) this;
        }

        public Criteria andCcodeIsNull() {
            addCriterion("cCode is null");
            return (Criteria) this;
        }

        public Criteria andCcodeIsNotNull() {
            addCriterion("cCode is not null");
            return (Criteria) this;
        }

        public Criteria andCcodeEqualTo(String value) {
            addCriterion("cCode =", value, "ccode");
            return (Criteria) this;
        }

        public Criteria andCcodeNotEqualTo(String value) {
            addCriterion("cCode <>", value, "ccode");
            return (Criteria) this;
        }

        public Criteria andCcodeGreaterThan(String value) {
            addCriterion("cCode >", value, "ccode");
            return (Criteria) this;
        }

        public Criteria andCcodeGreaterThanOrEqualTo(String value) {
            addCriterion("cCode >=", value, "ccode");
            return (Criteria) this;
        }

        public Criteria andCcodeLessThan(String value) {
            addCriterion("cCode <", value, "ccode");
            return (Criteria) this;
        }

        public Criteria andCcodeLessThanOrEqualTo(String value) {
            addCriterion("cCode <=", value, "ccode");
            return (Criteria) this;
        }

        public Criteria andCcodeLike(String value) {
            addCriterion("cCode like", value, "ccode");
            return (Criteria) this;
        }

        public Criteria andCcodeNotLike(String value) {
            addCriterion("cCode not like", value, "ccode");
            return (Criteria) this;
        }

        public Criteria andCcodeIn(List<String> values) {
            addCriterion("cCode in", values, "ccode");
            return (Criteria) this;
        }

        public Criteria andCcodeNotIn(List<String> values) {
            addCriterion("cCode not in", values, "ccode");
            return (Criteria) this;
        }

        public Criteria andCcodeBetween(String value1, String value2) {
            addCriterion("cCode between", value1, value2, "ccode");
            return (Criteria) this;
        }

        public Criteria andCcodeNotBetween(String value1, String value2) {
            addCriterion("cCode not between", value1, value2, "ccode");
            return (Criteria) this;
        }

        public Criteria andCnameIsNull() {
            addCriterion("cName is null");
            return (Criteria) this;
        }

        public Criteria andCnameIsNotNull() {
            addCriterion("cName is not null");
            return (Criteria) this;
        }

        public Criteria andCnameEqualTo(String value) {
            addCriterion("cName =", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameNotEqualTo(String value) {
            addCriterion("cName <>", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameGreaterThan(String value) {
            addCriterion("cName >", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameGreaterThanOrEqualTo(String value) {
            addCriterion("cName >=", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameLessThan(String value) {
            addCriterion("cName <", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameLessThanOrEqualTo(String value) {
            addCriterion("cName <=", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameLike(String value) {
            addCriterion("cName like", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameNotLike(String value) {
            addCriterion("cName not like", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameIn(List<String> values) {
            addCriterion("cName in", values, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameNotIn(List<String> values) {
            addCriterion("cName not in", values, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameBetween(String value1, String value2) {
            addCriterion("cName between", value1, value2, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameNotBetween(String value1, String value2) {
            addCriterion("cName not between", value1, value2, "cname");
            return (Criteria) this;
        }

        public Criteria andCprinttemplateidIsNull() {
            addCriterion("cPrintTemplateID is null");
            return (Criteria) this;
        }

        public Criteria andCprinttemplateidIsNotNull() {
            addCriterion("cPrintTemplateID is not null");
            return (Criteria) this;
        }

        public Criteria andCprinttemplateidEqualTo(String value) {
            addCriterion("cPrintTemplateID =", value, "cprinttemplateid");
            return (Criteria) this;
        }

        public Criteria andCprinttemplateidNotEqualTo(String value) {
            addCriterion("cPrintTemplateID <>", value, "cprinttemplateid");
            return (Criteria) this;
        }

        public Criteria andCprinttemplateidGreaterThan(String value) {
            addCriterion("cPrintTemplateID >", value, "cprinttemplateid");
            return (Criteria) this;
        }

        public Criteria andCprinttemplateidGreaterThanOrEqualTo(String value) {
            addCriterion("cPrintTemplateID >=", value, "cprinttemplateid");
            return (Criteria) this;
        }

        public Criteria andCprinttemplateidLessThan(String value) {
            addCriterion("cPrintTemplateID <", value, "cprinttemplateid");
            return (Criteria) this;
        }

        public Criteria andCprinttemplateidLessThanOrEqualTo(String value) {
            addCriterion("cPrintTemplateID <=", value, "cprinttemplateid");
            return (Criteria) this;
        }

        public Criteria andCprinttemplateidLike(String value) {
            addCriterion("cPrintTemplateID like", value, "cprinttemplateid");
            return (Criteria) this;
        }

        public Criteria andCprinttemplateidNotLike(String value) {
            addCriterion("cPrintTemplateID not like", value, "cprinttemplateid");
            return (Criteria) this;
        }

        public Criteria andCprinttemplateidIn(List<String> values) {
            addCriterion("cPrintTemplateID in", values, "cprinttemplateid");
            return (Criteria) this;
        }

        public Criteria andCprinttemplateidNotIn(List<String> values) {
            addCriterion("cPrintTemplateID not in", values, "cprinttemplateid");
            return (Criteria) this;
        }

        public Criteria andCprinttemplateidBetween(String value1, String value2) {
            addCriterion("cPrintTemplateID between", value1, value2, "cprinttemplateid");
            return (Criteria) this;
        }

        public Criteria andCprinttemplateidNotBetween(String value1, String value2) {
            addCriterion("cPrintTemplateID not between", value1, value2, "cprinttemplateid");
            return (Criteria) this;
        }

        public Criteria andCcreaterIsNull() {
            addCriterion("cCreater is null");
            return (Criteria) this;
        }

        public Criteria andCcreaterIsNotNull() {
            addCriterion("cCreater is not null");
            return (Criteria) this;
        }

        public Criteria andCcreaterEqualTo(String value) {
            addCriterion("cCreater =", value, "ccreater");
            return (Criteria) this;
        }

        public Criteria andCcreaterNotEqualTo(String value) {
            addCriterion("cCreater <>", value, "ccreater");
            return (Criteria) this;
        }

        public Criteria andCcreaterGreaterThan(String value) {
            addCriterion("cCreater >", value, "ccreater");
            return (Criteria) this;
        }

        public Criteria andCcreaterGreaterThanOrEqualTo(String value) {
            addCriterion("cCreater >=", value, "ccreater");
            return (Criteria) this;
        }

        public Criteria andCcreaterLessThan(String value) {
            addCriterion("cCreater <", value, "ccreater");
            return (Criteria) this;
        }

        public Criteria andCcreaterLessThanOrEqualTo(String value) {
            addCriterion("cCreater <=", value, "ccreater");
            return (Criteria) this;
        }

        public Criteria andCcreaterLike(String value) {
            addCriterion("cCreater like", value, "ccreater");
            return (Criteria) this;
        }

        public Criteria andCcreaterNotLike(String value) {
            addCriterion("cCreater not like", value, "ccreater");
            return (Criteria) this;
        }

        public Criteria andCcreaterIn(List<String> values) {
            addCriterion("cCreater in", values, "ccreater");
            return (Criteria) this;
        }

        public Criteria andCcreaterNotIn(List<String> values) {
            addCriterion("cCreater not in", values, "ccreater");
            return (Criteria) this;
        }

        public Criteria andCcreaterBetween(String value1, String value2) {
            addCriterion("cCreater between", value1, value2, "ccreater");
            return (Criteria) this;
        }

        public Criteria andCcreaterNotBetween(String value1, String value2) {
            addCriterion("cCreater not between", value1, value2, "ccreater");
            return (Criteria) this;
        }

        public Criteria andCcreatedateIsNull() {
            addCriterion("cCreateDate is null");
            return (Criteria) this;
        }

        public Criteria andCcreatedateIsNotNull() {
            addCriterion("cCreateDate is not null");
            return (Criteria) this;
        }

        public Criteria andCcreatedateEqualTo(Date value) {
            addCriterion("cCreateDate =", value, "ccreatedate");
            return (Criteria) this;
        }

        public Criteria andCcreatedateNotEqualTo(Date value) {
            addCriterion("cCreateDate <>", value, "ccreatedate");
            return (Criteria) this;
        }

        public Criteria andCcreatedateGreaterThan(Date value) {
            addCriterion("cCreateDate >", value, "ccreatedate");
            return (Criteria) this;
        }

        public Criteria andCcreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("cCreateDate >=", value, "ccreatedate");
            return (Criteria) this;
        }

        public Criteria andCcreatedateLessThan(Date value) {
            addCriterion("cCreateDate <", value, "ccreatedate");
            return (Criteria) this;
        }

        public Criteria andCcreatedateLessThanOrEqualTo(Date value) {
            addCriterion("cCreateDate <=", value, "ccreatedate");
            return (Criteria) this;
        }

        public Criteria andCcreatedateIn(List<Date> values) {
            addCriterion("cCreateDate in", values, "ccreatedate");
            return (Criteria) this;
        }

        public Criteria andCcreatedateNotIn(List<Date> values) {
            addCriterion("cCreateDate not in", values, "ccreatedate");
            return (Criteria) this;
        }

        public Criteria andCcreatedateBetween(Date value1, Date value2) {
            addCriterion("cCreateDate between", value1, value2, "ccreatedate");
            return (Criteria) this;
        }

        public Criteria andCcreatedateNotBetween(Date value1, Date value2) {
            addCriterion("cCreateDate not between", value1, value2, "ccreatedate");
            return (Criteria) this;
        }

        public Criteria andCupdaterIsNull() {
            addCriterion("cUpdater is null");
            return (Criteria) this;
        }

        public Criteria andCupdaterIsNotNull() {
            addCriterion("cUpdater is not null");
            return (Criteria) this;
        }

        public Criteria andCupdaterEqualTo(String value) {
            addCriterion("cUpdater =", value, "cupdater");
            return (Criteria) this;
        }

        public Criteria andCupdaterNotEqualTo(String value) {
            addCriterion("cUpdater <>", value, "cupdater");
            return (Criteria) this;
        }

        public Criteria andCupdaterGreaterThan(String value) {
            addCriterion("cUpdater >", value, "cupdater");
            return (Criteria) this;
        }

        public Criteria andCupdaterGreaterThanOrEqualTo(String value) {
            addCriterion("cUpdater >=", value, "cupdater");
            return (Criteria) this;
        }

        public Criteria andCupdaterLessThan(String value) {
            addCriterion("cUpdater <", value, "cupdater");
            return (Criteria) this;
        }

        public Criteria andCupdaterLessThanOrEqualTo(String value) {
            addCriterion("cUpdater <=", value, "cupdater");
            return (Criteria) this;
        }

        public Criteria andCupdaterLike(String value) {
            addCriterion("cUpdater like", value, "cupdater");
            return (Criteria) this;
        }

        public Criteria andCupdaterNotLike(String value) {
            addCriterion("cUpdater not like", value, "cupdater");
            return (Criteria) this;
        }

        public Criteria andCupdaterIn(List<String> values) {
            addCriterion("cUpdater in", values, "cupdater");
            return (Criteria) this;
        }

        public Criteria andCupdaterNotIn(List<String> values) {
            addCriterion("cUpdater not in", values, "cupdater");
            return (Criteria) this;
        }

        public Criteria andCupdaterBetween(String value1, String value2) {
            addCriterion("cUpdater between", value1, value2, "cupdater");
            return (Criteria) this;
        }

        public Criteria andCupdaterNotBetween(String value1, String value2) {
            addCriterion("cUpdater not between", value1, value2, "cupdater");
            return (Criteria) this;
        }

        public Criteria andCupdatedateIsNull() {
            addCriterion("cUpdateDate is null");
            return (Criteria) this;
        }

        public Criteria andCupdatedateIsNotNull() {
            addCriterion("cUpdateDate is not null");
            return (Criteria) this;
        }

        public Criteria andCupdatedateEqualTo(Date value) {
            addCriterion("cUpdateDate =", value, "cupdatedate");
            return (Criteria) this;
        }

        public Criteria andCupdatedateNotEqualTo(Date value) {
            addCriterion("cUpdateDate <>", value, "cupdatedate");
            return (Criteria) this;
        }

        public Criteria andCupdatedateGreaterThan(Date value) {
            addCriterion("cUpdateDate >", value, "cupdatedate");
            return (Criteria) this;
        }

        public Criteria andCupdatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("cUpdateDate >=", value, "cupdatedate");
            return (Criteria) this;
        }

        public Criteria andCupdatedateLessThan(Date value) {
            addCriterion("cUpdateDate <", value, "cupdatedate");
            return (Criteria) this;
        }

        public Criteria andCupdatedateLessThanOrEqualTo(Date value) {
            addCriterion("cUpdateDate <=", value, "cupdatedate");
            return (Criteria) this;
        }

        public Criteria andCupdatedateIn(List<Date> values) {
            addCriterion("cUpdateDate in", values, "cupdatedate");
            return (Criteria) this;
        }

        public Criteria andCupdatedateNotIn(List<Date> values) {
            addCriterion("cUpdateDate not in", values, "cupdatedate");
            return (Criteria) this;
        }

        public Criteria andCupdatedateBetween(Date value1, Date value2) {
            addCriterion("cUpdateDate between", value1, value2, "cupdatedate");
            return (Criteria) this;
        }

        public Criteria andCupdatedateNotBetween(Date value1, Date value2) {
            addCriterion("cUpdateDate not between", value1, value2, "cupdatedate");
            return (Criteria) this;
        }

        public Criteria andCtimestampIsNull() {
            addCriterion("cTimeStamp is null");
            return (Criteria) this;
        }

        public Criteria andCtimestampIsNotNull() {
            addCriterion("cTimeStamp is not null");
            return (Criteria) this;
        }

        public Criteria andCtimestampEqualTo(String value) {
            addCriterion("cTimeStamp =", value, "ctimestamp");
            return (Criteria) this;
        }

        public Criteria andCtimestampNotEqualTo(String value) {
            addCriterion("cTimeStamp <>", value, "ctimestamp");
            return (Criteria) this;
        }

        public Criteria andCtimestampGreaterThan(String value) {
            addCriterion("cTimeStamp >", value, "ctimestamp");
            return (Criteria) this;
        }

        public Criteria andCtimestampGreaterThanOrEqualTo(String value) {
            addCriterion("cTimeStamp >=", value, "ctimestamp");
            return (Criteria) this;
        }

        public Criteria andCtimestampLessThan(String value) {
            addCriterion("cTimeStamp <", value, "ctimestamp");
            return (Criteria) this;
        }

        public Criteria andCtimestampLessThanOrEqualTo(String value) {
            addCriterion("cTimeStamp <=", value, "ctimestamp");
            return (Criteria) this;
        }

        public Criteria andCtimestampLike(String value) {
            addCriterion("cTimeStamp like", value, "ctimestamp");
            return (Criteria) this;
        }

        public Criteria andCtimestampNotLike(String value) {
            addCriterion("cTimeStamp not like", value, "ctimestamp");
            return (Criteria) this;
        }

        public Criteria andCtimestampIn(List<String> values) {
            addCriterion("cTimeStamp in", values, "ctimestamp");
            return (Criteria) this;
        }

        public Criteria andCtimestampNotIn(List<String> values) {
            addCriterion("cTimeStamp not in", values, "ctimestamp");
            return (Criteria) this;
        }

        public Criteria andCtimestampBetween(String value1, String value2) {
            addCriterion("cTimeStamp between", value1, value2, "ctimestamp");
            return (Criteria) this;
        }

        public Criteria andCtimestampNotBetween(String value1, String value2) {
            addCriterion("cTimeStamp not between", value1, value2, "ctimestamp");
            return (Criteria) this;
        }

        public Criteria andInitialIsNull() {
            addCriterion("initial is null");
            return (Criteria) this;
        }

        public Criteria andInitialIsNotNull() {
            addCriterion("initial is not null");
            return (Criteria) this;
        }

        public Criteria andInitialEqualTo(String value) {
            addCriterion("initial =", value, "initial");
            return (Criteria) this;
        }

        public Criteria andInitialNotEqualTo(String value) {
            addCriterion("initial <>", value, "initial");
            return (Criteria) this;
        }

        public Criteria andInitialGreaterThan(String value) {
            addCriterion("initial >", value, "initial");
            return (Criteria) this;
        }

        public Criteria andInitialGreaterThanOrEqualTo(String value) {
            addCriterion("initial >=", value, "initial");
            return (Criteria) this;
        }

        public Criteria andInitialLessThan(String value) {
            addCriterion("initial <", value, "initial");
            return (Criteria) this;
        }

        public Criteria andInitialLessThanOrEqualTo(String value) {
            addCriterion("initial <=", value, "initial");
            return (Criteria) this;
        }

        public Criteria andInitialLike(String value) {
            addCriterion("initial like", value, "initial");
            return (Criteria) this;
        }

        public Criteria andInitialNotLike(String value) {
            addCriterion("initial not like", value, "initial");
            return (Criteria) this;
        }

        public Criteria andInitialIn(List<String> values) {
            addCriterion("initial in", values, "initial");
            return (Criteria) this;
        }

        public Criteria andInitialNotIn(List<String> values) {
            addCriterion("initial not in", values, "initial");
            return (Criteria) this;
        }

        public Criteria andInitialBetween(String value1, String value2) {
            addCriterion("initial between", value1, value2, "initial");
            return (Criteria) this;
        }

        public Criteria andInitialNotBetween(String value1, String value2) {
            addCriterion("initial not between", value1, value2, "initial");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.itsm_service_InstallTemplate
     *
     * @mbggenerated do_not_delete_during_merge Thu Dec 18 14:25:28 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.itsm_service_InstallTemplate
     *
     * @mbggenerated Thu Dec 18 14:25:28 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}