package com.wos.pojo;

import java.util.Date;

public class MaintainDocument {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cEventID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ceventid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ccode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cEnterpriseID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String centerpriseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cTaxCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ctaxcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cEnterpriseName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String centerprisename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cBelongTax
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cbelongtax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cEnterpriseAdress
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String centerpriseadress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cEnterpriseDepartment
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String centerprisedepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cContactID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ccontactid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cContactName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ccontactname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cContactTel
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ccontacttel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cContactPhone
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ccontactphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cProductID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cproductid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cInstallDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date cinstalldate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cMachineInfo
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cmachineinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cSoftwareVersion
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String csoftwareversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cEnvironment
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cenvironment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cDepartment
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cdepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cArea
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String carea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cFaultDescription
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cfaultdescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cResolvent
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cresolvent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cEmployeeID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cemployeeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cServiceType
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Integer cservicetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cIsCharge
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Integer cischarge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cMoney
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Double cmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cRepairDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date crepairdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cEndDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date cenddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cStatus
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Integer cstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cCreater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ccreater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cCreateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date ccreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cAuditorGuid
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cauditorguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cAuditTime
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date caudittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cLastUpdater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String clastupdater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cLastUpdateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date clastupdatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cRemark
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ctimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cOthers
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cothers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.cCustomerSign
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ccustomersign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.isAuditingQualified
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Integer isauditingqualified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.isAuditingEffective
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Integer isauditingeffective;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.NoQualifiedReason
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String noqualifiedreason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_service_MaintainDocument.USER_DEFINE10
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Integer userDefine10;
    
    private EnterpriseBaseInfo enterpriseBaseInfo;
    
    private Employee employee;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cGUID
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCguid() {
        return cguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cGUID
     *
     * @param cguid the value for dbo.itsm_service_MaintainDocument.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCguid(String cguid) {
        this.cguid = cguid == null ? null : cguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cEventID
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cEventID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCeventid() {
        return ceventid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cEventID
     *
     * @param ceventid the value for dbo.itsm_service_MaintainDocument.cEventID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCeventid(String ceventid) {
        this.ceventid = ceventid == null ? null : ceventid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cCode
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCcode() {
        return ccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cCode
     *
     * @param ccode the value for dbo.itsm_service_MaintainDocument.cCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcode(String ccode) {
        this.ccode = ccode == null ? null : ccode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cEnterpriseID
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cEnterpriseID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCenterpriseid() {
        return centerpriseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cEnterpriseID
     *
     * @param centerpriseid the value for dbo.itsm_service_MaintainDocument.cEnterpriseID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCenterpriseid(String centerpriseid) {
        this.centerpriseid = centerpriseid == null ? null : centerpriseid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cTaxCode
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cTaxCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCtaxcode() {
        return ctaxcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cTaxCode
     *
     * @param ctaxcode the value for dbo.itsm_service_MaintainDocument.cTaxCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCtaxcode(String ctaxcode) {
        this.ctaxcode = ctaxcode == null ? null : ctaxcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cEnterpriseName
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cEnterpriseName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCenterprisename() {
        return centerprisename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cEnterpriseName
     *
     * @param centerprisename the value for dbo.itsm_service_MaintainDocument.cEnterpriseName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCenterprisename(String centerprisename) {
        this.centerprisename = centerprisename == null ? null : centerprisename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cBelongTax
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cBelongTax
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCbelongtax() {
        return cbelongtax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cBelongTax
     *
     * @param cbelongtax the value for dbo.itsm_service_MaintainDocument.cBelongTax
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCbelongtax(String cbelongtax) {
        this.cbelongtax = cbelongtax == null ? null : cbelongtax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cEnterpriseAdress
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cEnterpriseAdress
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCenterpriseadress() {
        return centerpriseadress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cEnterpriseAdress
     *
     * @param centerpriseadress the value for dbo.itsm_service_MaintainDocument.cEnterpriseAdress
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCenterpriseadress(String centerpriseadress) {
        this.centerpriseadress = centerpriseadress == null ? null : centerpriseadress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cEnterpriseDepartment
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cEnterpriseDepartment
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCenterprisedepartment() {
        return centerprisedepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cEnterpriseDepartment
     *
     * @param centerprisedepartment the value for dbo.itsm_service_MaintainDocument.cEnterpriseDepartment
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCenterprisedepartment(String centerprisedepartment) {
        this.centerprisedepartment = centerprisedepartment == null ? null : centerprisedepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cContactID
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cContactID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCcontactid() {
        return ccontactid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cContactID
     *
     * @param ccontactid the value for dbo.itsm_service_MaintainDocument.cContactID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcontactid(String ccontactid) {
        this.ccontactid = ccontactid == null ? null : ccontactid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cContactName
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cContactName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCcontactname() {
        return ccontactname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cContactName
     *
     * @param ccontactname the value for dbo.itsm_service_MaintainDocument.cContactName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcontactname(String ccontactname) {
        this.ccontactname = ccontactname == null ? null : ccontactname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cContactTel
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cContactTel
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCcontacttel() {
        return ccontacttel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cContactTel
     *
     * @param ccontacttel the value for dbo.itsm_service_MaintainDocument.cContactTel
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcontacttel(String ccontacttel) {
        this.ccontacttel = ccontacttel == null ? null : ccontacttel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cContactPhone
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cContactPhone
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCcontactphone() {
        return ccontactphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cContactPhone
     *
     * @param ccontactphone the value for dbo.itsm_service_MaintainDocument.cContactPhone
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcontactphone(String ccontactphone) {
        this.ccontactphone = ccontactphone == null ? null : ccontactphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cProductID
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cProductID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCproductid() {
        return cproductid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cProductID
     *
     * @param cproductid the value for dbo.itsm_service_MaintainDocument.cProductID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCproductid(String cproductid) {
        this.cproductid = cproductid == null ? null : cproductid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cInstallDate
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cInstallDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getCinstalldate() {
        return cinstalldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cInstallDate
     *
     * @param cinstalldate the value for dbo.itsm_service_MaintainDocument.cInstallDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCinstalldate(Date cinstalldate) {
        this.cinstalldate = cinstalldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cMachineInfo
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cMachineInfo
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCmachineinfo() {
        return cmachineinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cMachineInfo
     *
     * @param cmachineinfo the value for dbo.itsm_service_MaintainDocument.cMachineInfo
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCmachineinfo(String cmachineinfo) {
        this.cmachineinfo = cmachineinfo == null ? null : cmachineinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cSoftwareVersion
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cSoftwareVersion
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCsoftwareversion() {
        return csoftwareversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cSoftwareVersion
     *
     * @param csoftwareversion the value for dbo.itsm_service_MaintainDocument.cSoftwareVersion
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCsoftwareversion(String csoftwareversion) {
        this.csoftwareversion = csoftwareversion == null ? null : csoftwareversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cEnvironment
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cEnvironment
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCenvironment() {
        return cenvironment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cEnvironment
     *
     * @param cenvironment the value for dbo.itsm_service_MaintainDocument.cEnvironment
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCenvironment(String cenvironment) {
        this.cenvironment = cenvironment == null ? null : cenvironment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cDepartment
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cDepartment
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCdepartment() {
        return cdepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cDepartment
     *
     * @param cdepartment the value for dbo.itsm_service_MaintainDocument.cDepartment
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCdepartment(String cdepartment) {
        this.cdepartment = cdepartment == null ? null : cdepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cArea
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cArea
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCarea() {
        return carea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cArea
     *
     * @param carea the value for dbo.itsm_service_MaintainDocument.cArea
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCarea(String carea) {
        this.carea = carea == null ? null : carea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cFaultDescription
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cFaultDescription
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCfaultdescription() {
        return cfaultdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cFaultDescription
     *
     * @param cfaultdescription the value for dbo.itsm_service_MaintainDocument.cFaultDescription
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCfaultdescription(String cfaultdescription) {
        this.cfaultdescription = cfaultdescription == null ? null : cfaultdescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cResolvent
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cResolvent
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCresolvent() {
        return cresolvent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cResolvent
     *
     * @param cresolvent the value for dbo.itsm_service_MaintainDocument.cResolvent
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCresolvent(String cresolvent) {
        this.cresolvent = cresolvent == null ? null : cresolvent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cEmployeeID
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cEmployeeID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCemployeeid() {
        return cemployeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cEmployeeID
     *
     * @param cemployeeid the value for dbo.itsm_service_MaintainDocument.cEmployeeID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCemployeeid(String cemployeeid) {
        this.cemployeeid = cemployeeid == null ? null : cemployeeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cServiceType
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cServiceType
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Integer getCservicetype() {
        return cservicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cServiceType
     *
     * @param cservicetype the value for dbo.itsm_service_MaintainDocument.cServiceType
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCservicetype(Integer cservicetype) {
        this.cservicetype = cservicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cIsCharge
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cIsCharge
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Integer getCischarge() {
        return cischarge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cIsCharge
     *
     * @param cischarge the value for dbo.itsm_service_MaintainDocument.cIsCharge
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCischarge(Integer cischarge) {
        this.cischarge = cischarge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cMoney
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cMoney
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Double getCmoney() {
        return cmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cMoney
     *
     * @param cmoney the value for dbo.itsm_service_MaintainDocument.cMoney
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCmoney(Double cmoney) {
        this.cmoney = cmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cRepairDate
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cRepairDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getCrepairdate() {
        return crepairdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cRepairDate
     *
     * @param crepairdate the value for dbo.itsm_service_MaintainDocument.cRepairDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCrepairdate(Date crepairdate) {
        this.crepairdate = crepairdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cEndDate
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cEndDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getCenddate() {
        return cenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cEndDate
     *
     * @param cenddate the value for dbo.itsm_service_MaintainDocument.cEndDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCenddate(Date cenddate) {
        this.cenddate = cenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cStatus
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cStatus
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Integer getCstatus() {
        return cstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cStatus
     *
     * @param cstatus the value for dbo.itsm_service_MaintainDocument.cStatus
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCstatus(Integer cstatus) {
        this.cstatus = cstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cCreater
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cCreater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCcreater() {
        return ccreater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cCreater
     *
     * @param ccreater the value for dbo.itsm_service_MaintainDocument.cCreater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcreater(String ccreater) {
        this.ccreater = ccreater == null ? null : ccreater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cCreateDate
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cCreateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getCcreatedate() {
        return ccreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cCreateDate
     *
     * @param ccreatedate the value for dbo.itsm_service_MaintainDocument.cCreateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcreatedate(Date ccreatedate) {
        this.ccreatedate = ccreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cAuditorGuid
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cAuditorGuid
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCauditorguid() {
        return cauditorguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cAuditorGuid
     *
     * @param cauditorguid the value for dbo.itsm_service_MaintainDocument.cAuditorGuid
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCauditorguid(String cauditorguid) {
        this.cauditorguid = cauditorguid == null ? null : cauditorguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cAuditTime
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cAuditTime
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getCaudittime() {
        return caudittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cAuditTime
     *
     * @param caudittime the value for dbo.itsm_service_MaintainDocument.cAuditTime
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCaudittime(Date caudittime) {
        this.caudittime = caudittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cLastUpdater
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cLastUpdater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getClastupdater() {
        return clastupdater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cLastUpdater
     *
     * @param clastupdater the value for dbo.itsm_service_MaintainDocument.cLastUpdater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setClastupdater(String clastupdater) {
        this.clastupdater = clastupdater == null ? null : clastupdater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cLastUpdateDate
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cLastUpdateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getClastupdatedate() {
        return clastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cLastUpdateDate
     *
     * @param clastupdatedate the value for dbo.itsm_service_MaintainDocument.cLastUpdateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setClastupdatedate(Date clastupdatedate) {
        this.clastupdatedate = clastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cRemark
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cRemark
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCremark() {
        return cremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cRemark
     *
     * @param cremark the value for dbo.itsm_service_MaintainDocument.cRemark
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCremark(String cremark) {
        this.cremark = cremark == null ? null : cremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cTimeStamp
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCtimestamp() {
        return ctimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cTimeStamp
     *
     * @param ctimestamp the value for dbo.itsm_service_MaintainDocument.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCtimestamp(String ctimestamp) {
        this.ctimestamp = ctimestamp == null ? null : ctimestamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cOthers
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cOthers
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCothers() {
        return cothers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cOthers
     *
     * @param cothers the value for dbo.itsm_service_MaintainDocument.cOthers
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCothers(String cothers) {
        this.cothers = cothers == null ? null : cothers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.cCustomerSign
     *
     * @return the value of dbo.itsm_service_MaintainDocument.cCustomerSign
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCcustomersign() {
        return ccustomersign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.cCustomerSign
     *
     * @param ccustomersign the value for dbo.itsm_service_MaintainDocument.cCustomerSign
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcustomersign(String ccustomersign) {
        this.ccustomersign = ccustomersign == null ? null : ccustomersign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.isAuditingQualified
     *
     * @return the value of dbo.itsm_service_MaintainDocument.isAuditingQualified
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Integer getIsauditingqualified() {
        return isauditingqualified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.isAuditingQualified
     *
     * @param isauditingqualified the value for dbo.itsm_service_MaintainDocument.isAuditingQualified
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setIsauditingqualified(Integer isauditingqualified) {
        this.isauditingqualified = isauditingqualified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.isAuditingEffective
     *
     * @return the value of dbo.itsm_service_MaintainDocument.isAuditingEffective
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Integer getIsauditingeffective() {
        return isauditingeffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.isAuditingEffective
     *
     * @param isauditingeffective the value for dbo.itsm_service_MaintainDocument.isAuditingEffective
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setIsauditingeffective(Integer isauditingeffective) {
        this.isauditingeffective = isauditingeffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.NoQualifiedReason
     *
     * @return the value of dbo.itsm_service_MaintainDocument.NoQualifiedReason
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getNoqualifiedreason() {
        return noqualifiedreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.NoQualifiedReason
     *
     * @param noqualifiedreason the value for dbo.itsm_service_MaintainDocument.NoQualifiedReason
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setNoqualifiedreason(String noqualifiedreason) {
        this.noqualifiedreason = noqualifiedreason == null ? null : noqualifiedreason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_service_MaintainDocument.USER_DEFINE10
     *
     * @return the value of dbo.itsm_service_MaintainDocument.USER_DEFINE10
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Integer getUserDefine10() {
        return userDefine10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_service_MaintainDocument.USER_DEFINE10
     *
     * @param userDefine10 the value for dbo.itsm_service_MaintainDocument.USER_DEFINE10
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setUserDefine10(Integer userDefine10) {
        this.userDefine10 = userDefine10;
    }

    public EnterpriseBaseInfo getEnterpriseBaseInfo()
    {
        return enterpriseBaseInfo;
    }

    public void setEnterpriseBaseInfo(EnterpriseBaseInfo enterpriseBaseInfo)
    {
        this.enterpriseBaseInfo = enterpriseBaseInfo;
    }

    public Employee getEmployee()
    {
        return employee;
    }

    public void setEmployee(Employee employee)
    {
        this.employee = employee;
    }
    
    
}