package com.wos.pojo;

public class MetaEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.META_ENTITY.cGuid
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.META_ENTITY.cTable
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ctable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.META_ENTITY.cName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.META_ENTITY.cEntityClass
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String centityclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.META_ENTITY.cShareMode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String csharemode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.META_ENTITY.cRemark
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.META_ENTITY.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ctimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.META_ENTITY.cFreeFlex
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cfreeflex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.META_ENTITY.cVirtual
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cvirtual;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.META_ENTITY.cViid
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cviid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.META_ENTITY.cWidgetType
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cwidgettype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.META_ENTITY.cBasicData
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cbasicdata;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.META_ENTITY.cEncodeControl
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cencodecontrol;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.META_ENTITY.cGuid
     *
     * @return the value of dbo.META_ENTITY.cGuid
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCguid() {
        return cguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.META_ENTITY.cGuid
     *
     * @param cguid the value for dbo.META_ENTITY.cGuid
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCguid(String cguid) {
        this.cguid = cguid == null ? null : cguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.META_ENTITY.cTable
     *
     * @return the value of dbo.META_ENTITY.cTable
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCtable() {
        return ctable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.META_ENTITY.cTable
     *
     * @param ctable the value for dbo.META_ENTITY.cTable
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCtable(String ctable) {
        this.ctable = ctable == null ? null : ctable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.META_ENTITY.cName
     *
     * @return the value of dbo.META_ENTITY.cName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.META_ENTITY.cName
     *
     * @param cname the value for dbo.META_ENTITY.cName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.META_ENTITY.cEntityClass
     *
     * @return the value of dbo.META_ENTITY.cEntityClass
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCentityclass() {
        return centityclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.META_ENTITY.cEntityClass
     *
     * @param centityclass the value for dbo.META_ENTITY.cEntityClass
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCentityclass(String centityclass) {
        this.centityclass = centityclass == null ? null : centityclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.META_ENTITY.cShareMode
     *
     * @return the value of dbo.META_ENTITY.cShareMode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCsharemode() {
        return csharemode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.META_ENTITY.cShareMode
     *
     * @param csharemode the value for dbo.META_ENTITY.cShareMode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCsharemode(String csharemode) {
        this.csharemode = csharemode == null ? null : csharemode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.META_ENTITY.cRemark
     *
     * @return the value of dbo.META_ENTITY.cRemark
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCremark() {
        return cremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.META_ENTITY.cRemark
     *
     * @param cremark the value for dbo.META_ENTITY.cRemark
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCremark(String cremark) {
        this.cremark = cremark == null ? null : cremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.META_ENTITY.cTimeStamp
     *
     * @return the value of dbo.META_ENTITY.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCtimestamp() {
        return ctimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.META_ENTITY.cTimeStamp
     *
     * @param ctimestamp the value for dbo.META_ENTITY.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCtimestamp(String ctimestamp) {
        this.ctimestamp = ctimestamp == null ? null : ctimestamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.META_ENTITY.cFreeFlex
     *
     * @return the value of dbo.META_ENTITY.cFreeFlex
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCfreeflex() {
        return cfreeflex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.META_ENTITY.cFreeFlex
     *
     * @param cfreeflex the value for dbo.META_ENTITY.cFreeFlex
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCfreeflex(String cfreeflex) {
        this.cfreeflex = cfreeflex == null ? null : cfreeflex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.META_ENTITY.cVirtual
     *
     * @return the value of dbo.META_ENTITY.cVirtual
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCvirtual() {
        return cvirtual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.META_ENTITY.cVirtual
     *
     * @param cvirtual the value for dbo.META_ENTITY.cVirtual
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCvirtual(String cvirtual) {
        this.cvirtual = cvirtual == null ? null : cvirtual.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.META_ENTITY.cViid
     *
     * @return the value of dbo.META_ENTITY.cViid
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCviid() {
        return cviid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.META_ENTITY.cViid
     *
     * @param cviid the value for dbo.META_ENTITY.cViid
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCviid(String cviid) {
        this.cviid = cviid == null ? null : cviid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.META_ENTITY.cWidgetType
     *
     * @return the value of dbo.META_ENTITY.cWidgetType
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCwidgettype() {
        return cwidgettype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.META_ENTITY.cWidgetType
     *
     * @param cwidgettype the value for dbo.META_ENTITY.cWidgetType
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCwidgettype(String cwidgettype) {
        this.cwidgettype = cwidgettype == null ? null : cwidgettype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.META_ENTITY.cBasicData
     *
     * @return the value of dbo.META_ENTITY.cBasicData
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCbasicdata() {
        return cbasicdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.META_ENTITY.cBasicData
     *
     * @param cbasicdata the value for dbo.META_ENTITY.cBasicData
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCbasicdata(String cbasicdata) {
        this.cbasicdata = cbasicdata == null ? null : cbasicdata.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.META_ENTITY.cEncodeControl
     *
     * @return the value of dbo.META_ENTITY.cEncodeControl
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCencodecontrol() {
        return cencodecontrol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.META_ENTITY.cEncodeControl
     *
     * @param cencodecontrol the value for dbo.META_ENTITY.cEncodeControl
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCencodecontrol(String cencodecontrol) {
        this.cencodecontrol = cencodecontrol == null ? null : cencodecontrol.trim();
    }
}