package com.wos.pojo;

public class SurveyDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_SurveyDetail.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_SurveyDetail.cSurveyID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String csurveyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_SurveyDetail.cItemID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String citemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_SurveyDetail.cItemValue
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String citemvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_SurveyDetail.USER_DEFINE10
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Integer userDefine10;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_SurveyDetail.cGUID
     *
     * @return the value of dbo.itsm_base_SurveyDetail.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCguid() {
        return cguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_SurveyDetail.cGUID
     *
     * @param cguid the value for dbo.itsm_base_SurveyDetail.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCguid(String cguid) {
        this.cguid = cguid == null ? null : cguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_SurveyDetail.cSurveyID
     *
     * @return the value of dbo.itsm_base_SurveyDetail.cSurveyID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCsurveyid() {
        return csurveyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_SurveyDetail.cSurveyID
     *
     * @param csurveyid the value for dbo.itsm_base_SurveyDetail.cSurveyID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCsurveyid(String csurveyid) {
        this.csurveyid = csurveyid == null ? null : csurveyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_SurveyDetail.cItemID
     *
     * @return the value of dbo.itsm_base_SurveyDetail.cItemID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCitemid() {
        return citemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_SurveyDetail.cItemID
     *
     * @param citemid the value for dbo.itsm_base_SurveyDetail.cItemID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCitemid(String citemid) {
        this.citemid = citemid == null ? null : citemid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_SurveyDetail.cItemValue
     *
     * @return the value of dbo.itsm_base_SurveyDetail.cItemValue
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCitemvalue() {
        return citemvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_SurveyDetail.cItemValue
     *
     * @param citemvalue the value for dbo.itsm_base_SurveyDetail.cItemValue
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCitemvalue(String citemvalue) {
        this.citemvalue = citemvalue == null ? null : citemvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_SurveyDetail.USER_DEFINE10
     *
     * @return the value of dbo.itsm_base_SurveyDetail.USER_DEFINE10
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Integer getUserDefine10() {
        return userDefine10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_SurveyDetail.USER_DEFINE10
     *
     * @param userDefine10 the value for dbo.itsm_base_SurveyDetail.USER_DEFINE10
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setUserDefine10(Integer userDefine10) {
        this.userDefine10 = userDefine10;
    }
}