package com.wos.pojo;

import java.util.Date;

public class TaxOrganization {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_TaxOrganization.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_TaxOrganization.cCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ccode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_TaxOrganization.cName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_TaxOrganization.cOrganizationCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String corganizationcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_TaxOrganization.cParentID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cparentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_TaxOrganization.cInnerCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cinnercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_TaxOrganization.iLeaf
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Integer ileaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_TaxOrganization.cCreater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ccreater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_TaxOrganization.cCreateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date ccreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_TaxOrganization.cUpdater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cupdater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_TaxOrganization.cUpdateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private Date cupdatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_TaxOrganization.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String ctimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.itsm_base_TaxOrganization.cFullName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    private String cfullname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_TaxOrganization.cGUID
     *
     * @return the value of dbo.itsm_base_TaxOrganization.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCguid() {
        return cguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_TaxOrganization.cGUID
     *
     * @param cguid the value for dbo.itsm_base_TaxOrganization.cGUID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCguid(String cguid) {
        this.cguid = cguid == null ? null : cguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_TaxOrganization.cCode
     *
     * @return the value of dbo.itsm_base_TaxOrganization.cCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCcode() {
        return ccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_TaxOrganization.cCode
     *
     * @param ccode the value for dbo.itsm_base_TaxOrganization.cCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcode(String ccode) {
        this.ccode = ccode == null ? null : ccode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_TaxOrganization.cName
     *
     * @return the value of dbo.itsm_base_TaxOrganization.cName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_TaxOrganization.cName
     *
     * @param cname the value for dbo.itsm_base_TaxOrganization.cName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_TaxOrganization.cOrganizationCode
     *
     * @return the value of dbo.itsm_base_TaxOrganization.cOrganizationCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCorganizationcode() {
        return corganizationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_TaxOrganization.cOrganizationCode
     *
     * @param corganizationcode the value for dbo.itsm_base_TaxOrganization.cOrganizationCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCorganizationcode(String corganizationcode) {
        this.corganizationcode = corganizationcode == null ? null : corganizationcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_TaxOrganization.cParentID
     *
     * @return the value of dbo.itsm_base_TaxOrganization.cParentID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCparentid() {
        return cparentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_TaxOrganization.cParentID
     *
     * @param cparentid the value for dbo.itsm_base_TaxOrganization.cParentID
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCparentid(String cparentid) {
        this.cparentid = cparentid == null ? null : cparentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_TaxOrganization.cInnerCode
     *
     * @return the value of dbo.itsm_base_TaxOrganization.cInnerCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCinnercode() {
        return cinnercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_TaxOrganization.cInnerCode
     *
     * @param cinnercode the value for dbo.itsm_base_TaxOrganization.cInnerCode
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCinnercode(String cinnercode) {
        this.cinnercode = cinnercode == null ? null : cinnercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_TaxOrganization.iLeaf
     *
     * @return the value of dbo.itsm_base_TaxOrganization.iLeaf
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Integer getIleaf() {
        return ileaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_TaxOrganization.iLeaf
     *
     * @param ileaf the value for dbo.itsm_base_TaxOrganization.iLeaf
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setIleaf(Integer ileaf) {
        this.ileaf = ileaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_TaxOrganization.cCreater
     *
     * @return the value of dbo.itsm_base_TaxOrganization.cCreater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCcreater() {
        return ccreater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_TaxOrganization.cCreater
     *
     * @param ccreater the value for dbo.itsm_base_TaxOrganization.cCreater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcreater(String ccreater) {
        this.ccreater = ccreater == null ? null : ccreater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_TaxOrganization.cCreateDate
     *
     * @return the value of dbo.itsm_base_TaxOrganization.cCreateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getCcreatedate() {
        return ccreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_TaxOrganization.cCreateDate
     *
     * @param ccreatedate the value for dbo.itsm_base_TaxOrganization.cCreateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCcreatedate(Date ccreatedate) {
        this.ccreatedate = ccreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_TaxOrganization.cUpdater
     *
     * @return the value of dbo.itsm_base_TaxOrganization.cUpdater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCupdater() {
        return cupdater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_TaxOrganization.cUpdater
     *
     * @param cupdater the value for dbo.itsm_base_TaxOrganization.cUpdater
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCupdater(String cupdater) {
        this.cupdater = cupdater == null ? null : cupdater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_TaxOrganization.cUpdateDate
     *
     * @return the value of dbo.itsm_base_TaxOrganization.cUpdateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public Date getCupdatedate() {
        return cupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_TaxOrganization.cUpdateDate
     *
     * @param cupdatedate the value for dbo.itsm_base_TaxOrganization.cUpdateDate
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCupdatedate(Date cupdatedate) {
        this.cupdatedate = cupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_TaxOrganization.cTimeStamp
     *
     * @return the value of dbo.itsm_base_TaxOrganization.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCtimestamp() {
        return ctimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_TaxOrganization.cTimeStamp
     *
     * @param ctimestamp the value for dbo.itsm_base_TaxOrganization.cTimeStamp
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCtimestamp(String ctimestamp) {
        this.ctimestamp = ctimestamp == null ? null : ctimestamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.itsm_base_TaxOrganization.cFullName
     *
     * @return the value of dbo.itsm_base_TaxOrganization.cFullName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public String getCfullname() {
        return cfullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.itsm_base_TaxOrganization.cFullName
     *
     * @param cfullname the value for dbo.itsm_base_TaxOrganization.cFullName
     *
     * @mbggenerated Mon Dec 01 16:05:56 CST 2014
     */
    public void setCfullname(String cfullname) {
        this.cfullname = cfullname == null ? null : cfullname.trim();
    }
}